### ISSUE TITLE
BRCM94322xxxx Big Sur

### ISSUE THREAD

**Issue by FotoFotoCheck** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#10]
This card, not work with BigSur. Anyone have tried it? ... BRCM943224HMS - EliteBook 8470p f.74 Conf.ID A1009D12 ...so work well on Catalina, didn't work in BigSur.. 'couse they stop support. 
No BT and no WiFi.
tried with airport fix...brcm without 460injection..nothing. With dsdt method, no change...with kext, OS won't load.

**Comment by chris1111** [comment]
You try to much thing before posting here the card work as it should I have 3 BRCM943224HMS working BS since the first Beta and work on finale release
