### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by jarmster** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#101]
Hey Chris. I’m running a 8470p with an i7-3820qm. 16 gigs of 1600. 
I have been testing your tool with big sur and I was able to create and install but after the post install I’m stuck on a black screen. It’s the 1600x900 screen to. The only way I can get it to boot to a desktop is if I include the  igfxvesa bootarg. I have catalina installed as well and it is acting the same way. I have a clover setup that boots Catalina perfectly but I’d like to try big sur and maybe OC if I can get it working. Got any ideas? Your guide is pretty straight forward and it not my first rodeo but I have no clue what the  issue could be.

**Comment by chris1111** [comment]
the guide support 1600x900 high screen, its alresdy test ; so follow corectly the guide
