### ISSUE TITLE
HP 8470P camera

### ISSUE THREAD

**Issue by eeff11** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#109]
My 8470P has i5-3210m,1366x768 display,bcm94322.
Well I'm new to opencore.

Follow strictly every step of Chris,installed big sur,found the camera not working.

Then installed Monterey,found before patching,there's already sound & wifi,after patching,no wifi,no sound,HD4000 works well with 1.5GB vram.I guess some nvram stored in the bios,need to delve into this later,even don't have to input wifi pass,already connected.

Then a third install of Monterey,this time no sound & wifi after installation,patched after installation,everything works.

Only the camera doesn't work.It shows up in the system information,but when launching the photobooth,the light did light up,but dark in the supposed camera capture area.

I tested with Ubuntu live,carema works normally.

What can I do to fix the camera?

The system information shows :
HP HD Webcam [fixed]:
Model Id: UVC Camera VendorID_1266 ProductID_45680
Unique ID: 0x1axxxxxxxxx

**Comment by chris1111** [comment]
Previouslly you have open discussion for an issue . [Rules about discussion](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/discussions/25)
If you are receive Email about my reply your certainely know why the Discussion you have open is deleted.
Anyway it's strange that I have to repeat it.

**Comment by eeff11** [comment]
Hi,Chris,

Thanks for letting me know.Forgive my ignorance of the rules,didn't spot that in the first place.Pls delete my thread in the discussion.

That's why I followed the rule of posting issues here.

What can I do to make the camera work,your camera working right? Is it possible the USB injection isn't correct in the Package?

thanks.

**Comment by chris1111** [comment]
Yes my camera works in macOS but not all HP camera works
what is the brand of the camera ? 
Cameras that don't show serial# are problematic. No known solution other than replacing the camera with one that is more compatible.

Does your webcam device have a serial# in the USB section?
See my CAM
<img width="624" alt="Screen Shot 2021-12-07 at 6 00 39 PM" src="https://user-images.githubusercontent.com/6248794/145119242-952630fb-5c23-4343-a186-cbd7b304fb97.png">

**Comment by eeff11** [comment]
Hi,

Thanks very much for your help.

My camera doesn't have a serial No in the USB section.
It's brand is Chicony,it is widely used.But if it's not compatible,then what other known brands for HP 8470P?

I'm going to replace the camera,but HP 8470P official service menu only list the spare part no for cam/microphone as 686045-001.

![Screen Shot 2021-12-08 at 7 55 32 AM](https://user-images.githubusercontent.com/4495422/145138936-02ff8e4b-6e34-4b1d-8d31-32c4562adf90.png)

**Comment by chris1111** [comment]
try to find Cam replacement from Ebay or amazon
