### ISSUE TITLE
Distorted screen content

### ISSUE THREAD

**Issue by noyannus** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#110]
Hi!

I can boot onto the installer, but after the first two blocks of boot screen text, the display changes to this:
![1](https://user-images.githubusercontent.com/6339921/145089854-e52c54f6-529c-40b0-ac7d-8d2f435ea6b8.JPG)

 And finishes with this:

![2](https://user-images.githubusercontent.com/6339921/145089887-b4b0975c-c1cf-4774-8bb8-6aed18c22d76.JPG)

When moving the mouse I can see something moving on that screen, so it does not hang/freeze. A resolution problem? I tried setting resolution to `1366x768,` or to `Max`, played with `forceResolution` and `reconnectOnResolutionChange` -- no change.

- latest HP-Probook-EliteBook-Package-Creator-OC 
- Monterey 12.0.1 or Big Sur 11.5.2
- Probook 4540s  (resolution 1366x768)

What am I doing wrong?

**Comment by chris1111** [comment]
You need to make Bios /Boot/ UEFI Hybrid with CSM
not UEFI native

**Comment by noyannus** [comment]
Thank you. I very much appreciate the quick help!

**Comment by Hack645** [comment]
But why does it behave like that, the boot resolution changes to 1024x768 and it's not really impressive to the eye even though it boots properly

**Comment by noyannus** [comment]
This thread is >2yrs old. The software has evolved since then. 

You might have better luck starting a fresh thread, with all the usual data (how to reproduce, versions of software and hardware, settings (bios) and configurations.
