### ISSUE TITLE
No boot 3740QM Elitebook 8470p

### ISSUE THREAD

**Issue by cleggorz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#111]
Hello I am not able to boot with my Elitebook 8470p I assume this is because I have upgraded the processor to a i7 3740QM, what steps would I need to take to fix this?

**Comment by chris1111** [comment]
this is not suppose to be a probleme if you have already install the Program without modification on EFI
Upload on zip here the EFI folder

**Comment by cleggorz** [comment]
Im just about to start my day job. I will upload as soon as I get home tonight, I have just finished a fresh install of Mojave and wiped EFI to do a fresh install. Thanks very much for the quick reply!

**Comment by cleggorz** [comment]
Closed because after a fresh install everything worked other than audio which I have opened a new issue for.
