### ISSUE TITLE
8470p No audio Mojave

### ISSUE THREAD

**Issue by cleggorz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#112]
So after a previous issue of my machine not booting after a fresh install everything works fine except audio. I have had exactly the same issue no matter how I try and load Macos on this machine (previously used Rehabmans Elitebook clover guide) I resorted to using this program in the hopes it would fix this issue. 

Awesome work by the way Chris! This has massively simplified the whole process of booting Macos on my machine!

Back to the no audio Issue I am completely stumped, This was never an issue back in the El capitan Days which I previously had working on this machine.

**Comment by cleggorz** [comment]
Deleted APPLE Folder just so I could upload here but OC and BOOT is present 

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7699234/EFI.zip)

**Comment by chris1111** [comment]
DSDT.aml is not create follow the guide
Mandatory Boot from USB Create  install Media HP installer, if not No DSDT was create

**Comment by cleggorz** [comment]
I have absolutely no idea, If I am being honest I used a previously existing install media that was clover based I think. Machine boots very fast and everything works great other than sound! I will start from scratch.

**Comment by chris1111** [comment]
You need start from scatch  to make DSDT.aml create with the patcher and Audio will working after booting from the Drive

**Comment by cleggorz** [comment]
So I started from scratch, my first problem is following the guide the usb installer will not boot at all. I followed your video guide step by step. I have gone back to the install I had working because DSDT.aml is in the OC/ORIGIN/ folder. I have found that audio will only work if I select AirportBrcmFixup.kext in the Post installer this completely breaks my Wifi though which is already a compatible card. For what reason would AirportBcrm fix my audio?

**Comment by chris1111** [comment]
I have many, many user with the 8470p without any issue for installing so you are probably missing some thing

**Comment by cleggorz** [comment]
I can attach my EFI folder again. I will completely delete it and run post installer. I will upload 2 one with AirportBcrmFixup.kext which will have working audio but kills my wifi and one without Airport fixup but audio will not work but wifi will. I will delete my EFI folder twice so I can do this. I am completely stumped why this isn't working correctly as this is not the first time i have installed MacOs on this laptop.

**Comment by cleggorz** [comment]
Ok by some unholy miracle I have fixed this. I do not understand how or why but basically I had to run the installer TWICE with the same options selected after a reboot. The first time running everything worked Other than audio. After a reboot and running the program again with the exact same selected options and another reboot audio started to work alongside my wifi.

**Comment by cleggorz** [comment]
After first install clearly no Audio but everything working. Rebooted and ran the installer again with the same options and now everything works. I have been deleting my EFI folder between installs previously just in case there are issues or conflicts. This is the first time I have reinstalled without deleting the EFI.

![Screenshot 2021-12-13 at 17 33 43](https://user-images.githubusercontent.com/40810427/145863359-1cbdc2c8-5686-4304-ba4a-8a62db3a9306.png)
![Screenshot 2021-12-13 at 17 34 04](https://user-images.githubusercontent.com/40810427/145863364-3c8b61b3-cee1-492b-b1f6-d4e567e8b53a.png)
![Screenshot 2021-12-13 at 17 37 19](https://user-images.githubusercontent.com/40810427/145863382-1796a4fd-361b-4df6-b9af-06a5d8f0cd95.png)

![Screenshot 2021-12-13 at 17 34 39](https://user-images.githubusercontent.com/40810427/145863372-1aa08366-7aeb-4dca-a8fa-9af43a19f846.png)

**Comment by chris1111** [comment]
Thats not work like this, you need booting and installing macOS from USB HP Media
the guide is verry clear anyway good luck
