### ISSUE TITLE
Are really only 4x0 G0 supported

### ISSUE THREAD

**Issue by fernsehmuell** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#118]
Hello,

i have a Probook 450G2 is this also supported?
In the readme only G0 is listed.
Can i do something to help supporting it?

regards
Udo

**Comment by chris1111** [comment]
Yes 4x0 G0 is a Ivy Bridge and the 450 G2  is Haswell 
Haswell is not support by this program
