### ISSUE TITLE
Not working on ProBook 4440s

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#12]
Not even booting on my i3 ProBook 4440s. Just a blank screen

**Comment by chris1111** [comment]
This is a great infos for help

**Comment by antoniojveraa** [comment]
Not much more to says... As I did with your HP-Probook-Elite-Package-Creator (Clover version), I followed step by step the tutorial. The package create the installation USB but does not boot to OC. No error messages, no nothing. Just a black screen. I'm not trying to install Big Sur but Catalina with OC.
![Captura de pantalla 2020-11-23 a las 7 39 18 a  m](https://user-images.githubusercontent.com/69108535/99935326-bd3e0200-2d60-11eb-8c61-431ef33cd581.png)

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/2#issuecomment-679373248

**Comment by antoniojveraa** [comment]
Here are hardware details:
[HWiNFO64 Report.pdf](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5582580/HWiNFO64.Report.pdf)

**Comment by chris1111** [comment]
Your laptop model and hardware are correct for BS with OC maybe juste trying a different USB port and 
make sur booting from the USB install drive
you can also try adding boot args -igfxvesa

**Comment by antoniojveraa** [comment]
I created again media install and tried in the four different ports of my laptop and same result: blank screen.
What do you mean with boot from the USB install drive??? I choose boot from EFI file, the select the USB and select the .EFI file. Right?
As Open Core does not boot I can not add any args. Do you mean editing the config file?

**Comment by antoniojveraa** [comment]
Hey Chris, in case you want to check, I'm attaching the OC EFI that I used to make my Ivy Bridge Probook 4440s work. Even WiFi is working with AR9485. When I followed the procedure on your post, the laptop never booted.
Any suggestion for tweaking will be appreciated.
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5652114/EFI.zip)
