### ISSUE TITLE
HP-Probook 6470b - No Sound, Brightness Control, Battery display

### ISSUE THREAD

**Issue by doob09** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#120]
Hi Chris,
 I have been successful in installing Big Sur using the newest Creator tool: https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/releases/tag/V1 . However, I do not have sound ,Brightness Control, Battery display.
 Any idea how to fix it ? 
 I am really appreciating your work. It really helps the installing process less painful.

**Comment by chris1111** [comment]
what is the exact model of your CPU because somes 6570b works on the HD 3000

**Comment by doob09** [comment]
CPU: Intel i5-3320M @2.6ghz

**Comment by chris1111** [comment]
Delete EFI from SSD then Reboot from USB and retry, I hope you have an SSD, not a old mechanical toshiba HD
after that post here the EFI folder on ZIP file

**Comment by doob09** [comment]
I have disable bluetooth  and  wifi kexts. It works very well now . Thanks !
