### ISSUE TITLE
8570p Monterey AirportBrcmFixup no wifi

### ISSUE THREAD

**Issue by sajtos888** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#122]
Hi!  I ran into another problem, installed 8570p Monterey and WiFi is not working.  If I enable AirportBrcmFixup kext the kernel will panic, if I disable it will start smoothly.

![20220306_151406](https://user-images.githubusercontent.com/70166390/156927455-56641b63-6512-4f30-961c-8cf4abc3146f.jpg)

io80211controller

**Comment by chris1111** [comment]
send EFI on ZIP file here

**Comment by sajtos888** [comment]
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8192935/EFI.zip)

**Comment by sajtos888** [comment]
i tried to give brcmfx-delay 15000 boot-args

**Comment by chris1111** [comment]
I have Wifi mini PCI Broadcom BCM943224HMS without issue
Probably relate to the wifi card? Is this a combo card Bluethoot and Wifi ?

**Comment by sajtos888** [comment]
not combined, bluetooth is separate but it works too

**Comment by sajtos888** [comment]
big sur is perfect wifi

**Comment by sudyhardy** [comment]
hi we have the same wifi card and this was my problem,
you can follow up the fix [HERE](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/124)

**Comment by chris1111** [comment]
[Fix](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/commit/0f5cf9efe600c1eb3b407bc24f97fc4ac4437fe0)
