### ISSUE TITLE
8470P using the latest Feb.18,still bootloop after first installation

### ISSUE THREAD

**Issue by eeff11** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#123]
Hi,

What info shall I provide.

Bootloop after first installation around 30 minutes. There's the installer after rebooting,and click this,still the installer.

**Comment by eeff11** [comment]
last version is Monterey 12.0.1,working fine.
Now need to update to the latest 12.2.1,wondering what's easiest way to update.
I used hotpatch with Clover before,most of the time small version update can just click in macOS,but this I'm sure not working since need patch HD4000,etc.

So instead of downloading the full 12.2.1,create install media,patch after install,any easier way?

thanks.

**Comment by chris1111** [comment]
You can Update any update, so update  to macOS 12.3 then after update reinstall HD 4000 Patcher
