### ISSUE TITLE
2570P Monterey SMCSuperIO stuck

### ISSUE THREAD

**Issue by sudyhardy** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#124]
Hi christ, thank you so much for this awesome project.

I tested in bigsur all was good.

but I just tested in monterey and I'm facing this problem. have any idea?
I attached my efi below
[Uploading EFI.zip…]()

![5D068C9C-1E63-491E-901F-0947072E0029](https://user-images.githubusercontent.com/54166117/159119420-3b9d5590-fd5a-4b14-815f-88e136816c88.jpeg)

**Comment by chris1111** [comment]
its not a broblem system boot anyway
I can take the same picture at this point

**Comment by sudyhardy** [comment]
> its not a broblem system boot anyway
> I can take the same picture at this point

**Comment by sudyhardy** [comment]
[Video bootloop](https://studentstesu-my.sharepoint.com/:v:/g/personal/sudi_hardi_students_tesu_edu/EfC4Na_DPm5Lg9-GmESEfT0BzKiIzuATztydx-w7UPCT5g?e=mJm0en) 

what's the problem? please help me

**Comment by chris1111** [comment]
Hey let the video continue

**Comment by sudyhardy** [comment]
> Hey let the video continue

it's restarting, I have another ssd with bigsur and use this monterey EFI and it's working, but this monterey os always restarting like that after post install

**Comment by chris1111** [comment]
Let the video continue and show me because I not see any reboot I just see same like me but your stop the video

[![Modular Image Creation](https://i87.servimg.com/u/f87/17/99/48/98/68747410.png)](https://drive.google.com/file/d/1-mYFQzaR1HchmqzbTqq7H5bdGzimqj6-/view?usp=sharing)

**Comment by sudyhardy** [comment]
[Video bootloop 2](https://studentstesu-my.sharepoint.com/:v:/g/personal/sudi_hardi_students_tesu_edu/EfUTDfPfr3VGom24z487izIB6-JRmS9q0mzt5CSUu-u_3Q?e=wvBkB2)

**Comment by chris1111** [comment]
try this
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8309275/config.plist.zip)

then show me video 
Boot or not boot

**Comment by sudyhardy** [comment]
[Video bootloop 3](https://studentstesu-my.sharepoint.com/:v:/g/personal/sudi_hardi_students_tesu_edu/ERoEVZ_MhS1Eh5E6GNNZQA0BUSIWVMh9zEBaJvxK1K3wqg?e=ba57xr)

it's restarting still

**Comment by chris1111** [comment]
Check the [Bios setup](https://mega.nz/folder/0wI2gaZC#Dn8u84CQlTkYzgvjCSMOow) of the laptop

**Comment by sudyhardy** [comment]
I was matching with your bios setup pdf that provided, but monterey still no luck for my laptop.
I'm using 12.3 btw

**Comment by sudyhardy** [comment]
Hi Chris!

so I disabled airportbrcmfixup kext and the monterey booted. but the problem is wifi not working and only bluetooth is working.
I use bcm4331 (wifi + bluetooth) .

I hope you feedback me what should I do? thanks.
![image](https://user-images.githubusercontent.com/54166117/159142509-55e9cb2e-3904-496e-aa58-03c7ee2768b0.jpg)

**Comment by chris1111** [comment]
If you have Internal Bluethoot in the laptop, Combo WIFI and bluthoot card can be cause the issue

**Comment by sudyhardy** [comment]
Chris,

thank you for your feedback..
so, I replaced airportbrcmfix to version 2.1.4 the latest and added bootarg (brcmfx-delay=15000 brcmfx-driver=3) the value 3 because my wificard is bcm4331 as explained in acidenthera github.

bluetooth and wifi are working now and I can use monterey, yay!
the installation is much easier and automated because of your work, you deserve donations!

**Comment by sudyhardy** [comment]
![Screenshot 2022-03-20 at 07 57 06](https://user-images.githubusercontent.com/54166117/159143588-92def765-fdef-473e-a0e9-87d444040e52.png)

**Comment by chris1111** [comment]
Great thanks

**Comment by chris1111** [comment]
what is the Model Exactly of the Mini PCI Wifi card?

**Comment by sudyhardy** [comment]
This one, I bought it online it's wifi + bluetooth

![Uploading E9ADB853-06F6-4C74-A944-EC49B3FCC5D9.jpeg…]()

**Comment by sudyhardy** [comment]
This one, I bought it online and it's wifi + bluetooth.

![IMG_5502](https://user-images.githubusercontent.com/54166117/159148771-fd913740-99c6-41f1-b1a5-1cda77f2b6b0.jpg)

**Comment by Muhal44** [comment]
My device is HP 6470b. My wifi card is also BCM943224HMS. I also have same wifi problem. Any problem in BigSur, but in Monterey wifi card is not working. If I use Airportbrcmfixup.kext with patched DSDT, it restarts repeatedly. If I use DSDT (without wifi patch), or when I try without DSDT, the computer turns on but does not see the wifi card.
Thanks far your contributions

**Comment by chris1111** [comment]
> My device is HP 6470b. My wifi card is also BCM943224HMS. I also have same wifi problem. Any problem in BigSur, but in Monterey wifi card is not working. If I use Airportbrcmfixup.kext with patched DSDT, it restarts repeatedly. If I use DSDT (without wifi patch), or when I try without DSDT, the computer turns on but does not see the wifi card.
> 
> Thanks far your contributions

DSDT is patch when you select BCM wifi option

**Comment by sudyhardy** [comment]
> My device is HP 6470b. My wifi card is also BCM943224HMS. I also have same wifi problem. Any problem in BigSur, but in Monterey wifi card is not working. If I use Airportbrcmfixup.kext with patched DSDT, it restarts repeatedly. If I use DSDT (without wifi patch), or when I try without DSDT, the computer turns on but does not see the wifi card. Thanks far your contributions

You better take out HP integrated Bluetooth 4.0+ EDR Wireless technology from the motherboard, as Chris mentioned that it caused the issue, because BCM943224HMS has already a bluetooth. that thing is like this..

![Bluetooth2 1-SPS537921-2](https://user-images.githubusercontent.com/54166117/159627528-8417fdd4-4316-4c52-9bab-8c9744964cd4.jpg)

**Comment by chris1111** [comment]
@sudyhardy I have BCM943224HMS without Bluetooth, this card is not Combo card
