### ISSUE TITLE
HP EliteBook 2570p

### ISSUE THREAD

**Issue by andrea-falco** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#125]
Hi,
I followed your guide and your videos.

After running the post-installation script and reboot, the PC goes in a boot loop.
Below you can see a video that start just before the end of installation:

[![Video](https://img.youtube.com/vi/tCntZ3W2gJo/0.jpg)](https://www.youtube.com/watch?v=tCntZ3W2gJo)

**My macOS:**
Big Sur 11.6.5 (20G527)

**My EFI folder:**
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8453381/EFI.zip)

**Comment by andrea-falco** [comment]
![Untitled](https://user-images.githubusercontent.com/23004377/162477675-f437f46b-c0f5-4edc-a938-310e1eb5d0ec.png)

**Comment by chris1111** [comment]
Use the USB Installer boot macOS Big Sur

Mount EFI

Change file 
[File.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8453566/File.zip)

Let me know if that fix

**Comment by andrea-falco** [comment]
Hi, I replaced the two files, but the PC still go in a boot loop.

My EFI folder:
[EFI_Chris.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8453983/EFI_Chris.zip)

**Comment by chris1111** [comment]
This is stange because I have the same Wifi card without any boot loop, the boot loop is already fix and confirming from me and other tester

**Comment by chris1111** [comment]
Try 2.1.3 Release
[AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup/releases/download/2.1.3/AirportBrcmFixup-2.1.3-RELEASE.zip)

**Comment by andrea-falco** [comment]
Hi Chris,
I noticed that the SMCSuperIO was missing (compared to my old installation), so I added the kext.

Now it's working.

My EFI folder:
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8456635/04_EFI.zip)

**Comment by chris1111** [comment]
The SMCSuperIO as nothing to do with this, the kext not working with the probook elitebook

**Comment by chris1111** [comment]
Here [This kext is only for Desktop](https://github.com/acidanthera/bugtracker/issues/577#issuecomment-554570850)
Any MacOS version  can live with out this plugins

**Comment by chris1111** [comment]
Big Sur (20G527) installed this morning
![Screen Shot 2022-04-09 at 7 08 48 AM](https://user-images.githubusercontent.com/6248794/162577868-634adaa2-8b0a-49f4-962a-7b46f8d53c74.png)
