### ISSUE TITLE
Multitouch capabilities of Synaptics Touchpad with VoodooPS2 2.2.9 (Acidanthera)

### ISSUE THREAD

**Issue by Muhal44** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#126]
Dear Chris
Maybe you know, but I wanted to share with you a situation I discovered by chance.

- I downloaded VoodooPS2 from [Kext Updater](https://update.kextupdater.de/kextupdater/Kext%20Updater.zip)/ Kextmanager/ NightlyBuilds
- I opened VoodooPS2Trackpad.kext's Info.plist file with PlistEditor
- I deleted ALPS GlidePoint and Elantech TouchPad under IOKitPersonalities. (it works even if it is not deleted, but it takes a long time to boot)
- I dumped it to EFI/OC/kext and processed it to the config file. (VoodooPS2Mouse.kext passive)
- I cleared the NVRAM while restarting the computer and the synaptics PS2 trackpad's multitouch features are now available.

NOTE1: Not Working: Trackpad's left and right physical buttons
NOTE2: The DEBUG version of VoodooPS2Controller.kext, which I got directly from Acidanthera's site, worked, but RELEASE does not work.

I hope you will find a solution to make the left and right buttons work.
I wish you good work.
I prepare my EFI with your HP-Probook-EliteBook-Package-Creator-OC program

**Comment by Muhal44** [comment]
My laptop is Probook 6470b

**Comment by juntomoon** [comment]
> My laptop is Probook 6470b

Bruh, thx for guide on multitouch, i take it, but have same problem lft/rght keys doesnt work.
Pls tell me, you find soluition ?

**Comment by Muhal44** [comment]
Sorry I haven't found a solution yet
