### ISSUE TITLE
HP 2570 Webcam

### ISSUE THREAD

**Issue by juntomoon** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#127]
I install your hack 2 times, big sur(1y ago) and now.
I update and clean install your monterey.
But in BigSur Webcam works fine, on Monterey i have only black screen.
Spec:
Bluetooth : Default Brcm Bluetooth(your fix)
Wi-Fi : Intel 7260 WI-FI(AirportItwlm fix)
CPU : I7-3740QM
Disk : SSD
Other Default.
Pls help, i have too much zoom conf on this laptop))
![CleanShot 2022-05-27 at 00 22 07](https://user-images.githubusercontent.com/103080029/170582308-f998a390-ef3e-4d2e-bb5e-721a23088f89.png)

**Comment by Muhal44** [comment]
Have you tried patching the USB port? Device may require extra power

**Comment by juntomoon** [comment]
Well now i dont have a solution for this.
I restore my big sur on flash drive and on BS camera working good.
[Uploading IO.zip…]()

Send here, my IORegistryExplorer file for BS and for Monterey
and screen in system settings
![CleanShot 2022-06-13 at 01 53 40](https://user-images.githubusercontent.com/103080029/174300264-d447b00b-3a42-4c97-8e0f-b01e5b9a1c6b.png)

**Comment by juntomoon** [comment]
UPD

**Comment by juntomoon** [comment]
Bruh, need help.

**Comment by farziro** [comment]
hi 
can i use this packeg creator for HP ZBOOK 17 g2 ????
