### ISSUE TITLE
Please add itlwm.Kext

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#128]
I have a wifi card AC7260 on my Probook 650 g1 I7 4712MQ

Please add support to install itlwm.kext in your software
And also add HeliPort in the Applications folder to control it. It's a replacement for the apple airport icon.
It works great! Thanks for your project

The ESPProMounter and OCAuxiliaryTools software are also a great combo. The last one edits config.plist and can generate  serial keys with one click.

**Comment by peekpt** [comment]
@chris1111 Thank you for your quick reply. Just one more question if you could answer me: My CPU is 8 core the one that is installed MacBook Pro 12,2 is a "i5 4 core". Can this affect performance?

**Comment by chris1111** [comment]
No way, you can change it if you want but it should do nothing more.
