### ISSUE TITLE
Elitebook 8470p WiFi and bluetooth from wake not working - everything else works

### ISSUE THREAD

**Issue by cable0429** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#129]
I have the Broadcom 4322 and if I if I use the kext - AirportBrcmFixup - it does not boot so I have it disabled in the config file

I have tried with the boot args - brcmfx-delay=15000 - however I can not get WiFi working, nor would it boot up

I applied the patches and everything works except bluetooth on wake, it does not reconnect....

I am attaching my files in case someone can help me resolve the WiFi not working

[HP-8470p-MBP.ioreg.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8934498/HP-8470p-MBP.ioreg.zip)

[SysDump-HP-8470p-MBP.spx.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8934499/SysDump-HP-8470p-MBP.spx.zip)

[OC.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/8934500/OC.zip)

**Comment by chris1111** [comment]
4322 its not a wifi BCM for me

**Comment by cable0429** [comment]
Shoot ok thanks

time to order a new one

**Comment by chris1111** [comment]
> Shoot ok thanks
> 
> time to order a new one


I mean what the exact model of the card

**Comment by cable0429** [comment]
DW 1510

![8C4F1FEA-CF21-4052-8363-8DF5C809686C](https://user-images.githubusercontent.com/103855920/174460679-9431380b-8fcd-46fd-bd5b-5b8a59ee5f52.jpeg)

**Comment by chris1111** [comment]
I dont know? its Broadcom BCM94322HM8L

**Comment by cable0429** [comment]
that is what I have, it matches the link on the read me page.

Anything I need to try or any recommendations to try?

**Comment by chris1111** [comment]
The  page recommandation link is

Wifi mini PCI Wifi mini PCI [AzureWave WLAN+BT BCM94352HMB](https://www.ebay.fr/itm/Azurewave-AW-CE123H-Broadcom-BCM94352-802-11ac-WiFi-card-Bluetooth-4-0-for-MAC-/272248789669) ebay
Wifi mini PCI Wifi mini PCI [AzureWave WLAN+BT BCM94352HMB](https://www.aliexpress.com/item/4000385703330.html) aliexpress
Wifi mini PCI Wifi mini PCI [Broadcom BCM943224HMS](https://www.ebay.com/itm/253022938877?hash=item3ae957a6fd:g:8JYAAMXQVT9TFoF4)
