### ISSUE TITLE
HP 8470P

### ISSUE THREAD

**Issue by eeff11** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#132]
Hi,
My HP 8470P was on 12.0.1 montery,everthing was fine.

Now the latest is 12.4,I was trying to upgrade,first download the latest May 20 patch,then select update in 12.0.1 to 12.4,then after initial installation,it boots to install monterey,and then it keeps rebooting.

Then prepare the 12.4 install media,wiped the HDD completely through USB install media,disk utility,then install,this time installed successfully.And then as before,disabled gatekeeper,using the May 20 patching,select everything patching and patching hd4000.

And then reboot,then it repeats itself rebooting,failed to booting into 12.4.
Selecting USB efi bootx64.efi,I can boot into 12.4,but no wifi,no bluetooth,no sound,they don't work as in 12.0.1.It's BCM94322.
I see hd4000 has been patched,Vram from 3mb to 1.5G.

Since this script is so wonderful,and my sincere thanks,but no clue at all what I can do.

So have to install 12.0.1 again for over an hour.

I asked before how to upgrade,the answer is updating and then patching,but somthing is wrong here.

What to do to update to 12.4?

**Comment by chris1111** [comment]
it is well to indicate in the guide that you must provide the LOG of the program and certainly the EFI file
