### ISSUE TITLE
Mac hot keys not working properly

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#134]
I did a fresh install today from your last 30 Jun update.  (HP 650 G1 8 series)

After installation I did the post install HP-ProBook-EliteBook-macOS.pkg for the EFI

Brightness and sound hot keys aren't working anymore without pressing the fn key.

ctrl and window keys seems to be switched

before:
ctrl = ctrl 
win = alt
alt = Mac

After update:

crtl = alt
win = ctrl
alt = Mac

I reverted to my old backup EFI from two days ago and the keys are working fine.

----
- Just a sidenote:
I switched my wifi to AirportItlwm.kext and it's working fine maybe you consider adding it as post install menu.

----
- One more thing:
Also noticed that OpenCore Configurator is on 0.8.0 version shouldn't it be on 0.8.2 ?

**Comment by chris1111** [comment]
Please read the post you need provide the complete install LOG if you need help about post install
