### ISSUE TITLE
Can't find packages to install.

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#136]
The post install "HP-ProBook-EliteBook-macOS.pkg"  returns can't find package to install message.

- git cloned
- open  Xcode & run - ok
- press build button - success
- open HP-ProBook-EliteBook-macOS.pkg
- tickboxes and did my config
- then it returns can't find package to install message

Where I can get the logs from the post install app?

**Comment by chris1111** [comment]
Read the page
[Build-Project](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/wiki/Build-Project)

**Comment by chris1111** [comment]
I just readd the .gitkeep tu build project xcode

**Comment by peekpt** [comment]
Going to try

**Comment by peekpt** [comment]
it's ok now, I still have to press fn for the hotkeys but I can leave with that.
Also I noticed prt screen is now for app screenshots instead the usual ^4
