### ISSUE TITLE
ACPI errors | Probook 6470b

### ISSUE THREAD

**Issue by wajwuz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#137]
Hi, recently i wanted to install Monterey on my second disk. I faced a lot of problems (most with unbootable usb, system wont boot after install or opencore wont recognize any device). How can i fix these errors (monterey instalator on startup). Sometimes it just stucks. (second image)

![C49E048E-0523-410F-AE35-2C83C2558409](https://user-images.githubusercontent.com/75165095/177017739-87b1db19-6d2a-457d-afef-6aa66e1b336d.jpeg)
![C253D7CB-3A61-44C2-B870-7B10DB4665FA](https://user-images.githubusercontent.com/75165095/177017740-3c16c17f-a52d-4e02-b967-d2f274663126.jpeg)

EFI on USB drive here
![image](https://user-images.githubusercontent.com/75165095/177017827-72c4bd9c-7289-421e-bad8-1b0558ba3ae5.jpg)

**Comment by chris1111** [comment]
ACPI eeror is normal for installing macOS 
This is gone after post install

**Comment by wajwuz** [comment]
If i complete the instalation i dont have bootable OS, either when opencore opens it doesnt shows any partition (only usb)

**Comment by chris1111** [comment]
Read the guide correctly
