### ISSUE TITLE
long boot

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#138]
[bootlog.txt](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/9034762/bootlog.txt)

I reverted to stable release 0.8.0 because 0.8.2 master was making the system very unstable and unresponsive. Sometimes I couldn't even type.

But despite that I always had some acpi bat and voodoo ps2 errors during boot. 
I was on a mechanical drive and did a new install a couple days ago because I switched to a new SSD . All feels more snappier now.
But  I'm facing a long boot problem, I have to wait sometimes 3 minutes to have the quick apple progress bar + login screen to happen.

Chris could you please take a look.
Thanks in advance

**Comment by chris1111** [comment]
it is relate to <IO80211FamilyLegacy`IO80211Controller::log so I think is Intel Wifi
Try with a compatible wifi

**Comment by peekpt** [comment]
I found the problem, it's the ssd (TRIM tooks 354s)  (Maybe not apple compatible)

Under: Kernel -> Block  
SetApfsTrimTimeout: 0 (was -1)

Now it takes seconds to boot. ( Maybe you may want to add this to your post install ?)

Wifi is fine I got a 800Mbps connection I have the 7260 wifi card
