### ISSUE TITLE
KP after wake on Probook 450 G0

### ISSUE THREAD

**Issue by Badarbuo** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#14]
Hi, my Probook works very well with your guide on Big Sur and Open Core. Only one issue, after a wake I got a kernel Panic like this 

(I have already tried to patch fine my Framebuffer and USB mapping without any success...) any idea? Thanks.

panic(cpu 4 caller 0xffffff8030d53a13): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since wake (130 seconds ago): 14, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since wake (130 seconds ago): 2, last successful checkin: 120 seconds ago

Backtrace (CPU 4), Frame : Return Address
0xffffffb0cdbb3670 : 0xffffff802dabc66d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffb0cdbb36c0 : 0xffffff802dbff073 mach_kernel : _kdp_i386_trap + 0x143
0xffffffb0cdbb3700 : 0xffffff802dbef6aa mach_kernel : _kernel_trap + 0x55a
0xffffffb0cdbb3750 : 0xffffff802da61a2f mach_kernel : _return_from_trap + 0xff
0xffffffb0cdbb3770 : 0xffffff802dabbf0d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffb0cdbb3890 : 0xffffff802dabc1f8 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffb0cdbb3900 : 0xffffff802e2bee84 mach_kernel : _panic_with_thread_context
0xffffffb0cdbb3970 : 0xffffff8030d53a13 com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffffb0cdbb3980 : 0xffffff8030d536ba com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xffffffb0cdbb39a0 : 0xffffff802e2460ee mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffffb0cdbb39f0 : 0xffffff8030d52b0a com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7c
0xffffffb0cdbb3b20 : 0xffffff802e2502bb mach_kernel : _is_io_connect_method + 0x35b
0xffffffb0cdbb3c80 : 0xffffff802dbaaa61 mach_kernel : _iokit_server_routine + 0x4d81
0xffffffb0cdbb3d90 : 0xffffff802dac1d77 mach_kernel : _ipc_kobject_server + 0x337
0xffffffb0cdbb3e00 : 0xffffff802da985d5 mach_kernel : _ipc_kmsg_send + 0x115
0xffffffb0cdbb3e60 : 0xffffff802daafb82 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffffb0cdbb3ef0 : 0xffffff802dbd3823 mach_kernel : _mach_call_munger64 + 0x273
0xffffffb0cdbb3fa0 : 0xffffff802da62216 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[7948A279-A8B8-3650-AFBF-B1E3EB68942A]@0xffffff8030d52000->0xffffff8030d53fff

Process name corresponding to current thread: watchdogd
Boot args: -v vsmcgen=1 keepsyms=1 -lilubeta alcid=13 swd_panic=1 darkwake=512 

Mac OS version:
20B29

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x000000002d800000
KernelCache base:  0xffffff802da00000
Kernel slide:      0x000000002d810000
Kernel text base:  0xffffff802da10000
__HIB  text base: 0xffffff802d900000
System model name: MacBookAir8,1 (Mac-827FAC58A8FDFA22)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 368564237145
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000055d02403fc
  Sleep   : 0x00000036d5cde1dc 0x000000034459f30c 0x0000000000000000
  Wake    : 0x00000036e2dcfd88 0x0000000045ceeb76 0x00000036d8978ddd

**Comment by Badarbuo** [comment]
My Config.plist

[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5612551/config.plist.zip)

**Comment by chris1111** [comment]
Return to default config.plist
also make sur ACPI config like this

![Capture d’écran, le 2020-11-29 à 13 46 07](https://user-images.githubusercontent.com/6248794/100550694-a0666a80-3249-11eb-9a27-ef0d01346057.png)

**Comment by Badarbuo** [comment]
i recreated the efi folder with your software but the problem persists, the desktop wakes up but no point is clickable and after a few seconds kernel panic. The ACPI config is how yours

**Comment by chris1111** [comment]
> i recreated the efi folder with your software but the problem persists, the desktop wakes up but no point is clickable and after a few seconds kernel panic. The ACPI config is how yours

you can not recreate EFI Folder with the programm, except if you did a full reinstall with the HP Create Install media so I don't think is the sase here.

**Comment by Badarbuo** [comment]
> > i recreated the efi folder with your software but the problem persists, the desktop wakes up but no point is clickable and after a few seconds kernel panic. The ACPI config is how yours
> 
> you can not recreate EFI Folder with the programm, except if you did a full reinstall with the HP Create Install media so I don't think is the case here.
> EDIT ***
> its very easy to see that you have modified several things in the configutation so please do not post an issue on a problem which should not be the original one.

No, i recreate original config AFTER your answer, now i have an original install but the issue Is the same

**Comment by chris1111** [comment]
Put your EFI Folder on zip here

**Comment by Badarbuo** [comment]
> Put your EFI Folder on zip here

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5612898/EFI.zip)

[My last KP.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5612899/My.last.KP.zip)

Thanks

**Comment by chris1111** [comment]
> > Put your EFI Folder on zip here
> 
> [EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5612898/EFI.zip)
> 
> [My last KP.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5612899/My.last.KP.zip)
> 
> Thanks

Why with the first config you have post here
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/14#issuecomment-735428854
IntelMausi is uncheck and RealtekRTL8111. is check then here your not have a RealtekRTL8111 in config you also don't have bluetooth to check and AirportBrcmFixup. Some things wrong here

**Comment by chris1111** [comment]
issue will be deletes
