### ISSUE TITLE
No boot after successful Monterey install 8470p

### ISSUE THREAD

**Issue by DANW-NZ** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#143]
After previously having a successfully working Monterey install on my 8470p I seem to be having problem after problem! I manage to successfully install Monterey, then run HP-ProBook-EliteBook-macOS.pkg. Everything seems to install fine (Gatekeeper obviously off). When I reboot I get the OC boot menu but after I select my install I get the message below and it stalls. I've tried reinstalling multiple times. It makes no difference if I boot from the SATA drive or the USB either. Any help appreciated.
![Screen Shot 2022-07-25 at 13 16 55](https://user-images.githubusercontent.com/107822196/180675378-a3a31aed-11d0-437b-bfef-494b9007fc82.png)

**Comment by DANW-NZ** [comment]
Just before the book menu appears this flashes up for a split second too, the file is definitely in the ACPI folder though.
![Screen Shot 2022-07-25 at 13 22 25](https://user-images.githubusercontent.com/107822196/180675793-4033cf71-1705-4756-9177-b19c7312e6ee.png)

**Comment by chris1111** [comment]
SPAME
