### ISSUE TITLE
Can't run the installer, error

### ISSUE THREAD

**Issue by DrMacabre** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#145]
Hello,

I'm trying to use your installer but it stops right after i select my USB key, i have disabled SIP and gatekeeper as per your instruction.
I'm on Big Sur 11.4 running with Opencore

![image](https://user-images.githubusercontent.com/49474452/185672629-97e3a6dd-05d4-4791-a6f2-a16ec7a9a952.png)

**Comment by chris1111** [comment]
SIP is not disable

**Comment by DrMacabre** [comment]
![image](https://user-images.githubusercontent.com/49474452/185676400-06c93a10-4241-4739-afcd-81c3f7f3fe1c.png)
it is not? i thought this was enough

**Comment by chris1111** [comment]
Why csr-active-config is set to  ➤ EF0F0000

**Comment by DrMacabre** [comment]
they say "FF0F0000 - Disable all flags in macOS Big Sur (0xfff) which has another new [flag for authenticated root](https://eclecticlight.co/2020/06/25/big-surs-signed-system-volume-added-security-protection/)"

taken from opencore install guide

**Comment by chris1111** [comment]
OpenCore: csrutil authenticated-root disable csr-active-config ➤ EF0F0000

**Comment by DrMacabre** [comment]
Fixed, thank you very much. :)
