### ISSUE TITLE
Monterey 12.5.1 on 4540s. After package installation I can't go into the boot screen.

### ISSUE THREAD

**Issue by superkahn** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#146]
Hi there. Thanks for all you do for the community!

I have a ProBook 4540s (C9K70UT#ABA) Intel Core i3 3rd Gen 3110M (2.40GHz) 16GB Memory - Intel HD Graphics 4000.

I was able to do a full installation of Monterey 12.5.1 using a real Mac on an external 2.5 sata 3 SSD.
To boot it up I used your custom EFI and added -no_compat_check to the custom boot flags
(*Note. I didn't install it with the install media guide you provided but with a real Mac because when I used the install media on the guide it didn't boot)

Package installation was successful but my issue is that after I reboot it gets stuck on the screen before the boot screen and never boots.
I been at this for hours.
I can't figure it out.
What can I do?  

*Edit*
I just read on the dortania.github that Ivy Bridge iGPUs are only supported up-to macOS 11.
So should I just give up on this installation?

**Comment by chris1111** [comment]
You are missing the most important infos! read the first page here, Dortania is not here

**Comment by superkahn** [comment]
I used the probook installer and finally installed but audio is not working. I got brightness, battery indicator, Icloud and iMessages working and was able to patch intel 4000 video and internet works fine.
The main issue I been trying to solve  for hours is get audio working but everything I do fails.
With Hackintool it shows me the audio device is disabled in the pcie tab and in the sound tab it shows me the device as IDT 92HD87B2/4 (0x76D9) (Online it say it has layout ID of 13) but it’s currently on layout id 12.
I have used almost every tool to fix this and nothing works.
I updated Lulu and applealac, then used SSDTTIme to patch and get SSDT-HPET.aml  and used propertree to update it and changed the layout ID to 13. Then I  reset system.efi on reboot. And booted without a problem, but now the battery indicator disappears. I have no idea what to do to anymore. I’m maybe thinking of downgrading from 12.5.1 to 12.4 and maybe fix this?
Would you know what the issue is?

**Comment by superkahn** [comment]
Here is my EFI file with everything that is working as I said above, but not the audio.

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/9467049/EFI.zip)

**Comment by superkahn** [comment]
Got it working nevermind.
