### ISSUE TITLE
build_userspace_exit_reason: illegal flags passed from userspace (some masked off) 0x101, ns: 20, code 0x1.

### ISSUE THREAD

**Issue by superkahn** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#147]
I am trying to run Monterey OS completely off a USB 64gb 3.0 drive. Installer ran fine like it did on my external and internal SSD but just as it’s trying to boot up to use Mac for the first time, I get this error on the usb which i didn’t get in either SSD’s.

build_userspace_exit_reason: illegal flags passed from userspace (some masked off) 0x101, ns: 20, code 0x1.

*Edit*: This Usb drive seems to be missing a user folder. The only folder that appears is shared.
So the installer is stuck in that last step and it won’t let go further.

How I can get the usb to boot?

**Comment by chris1111** [comment]
Post picture of USB and boot screen

**Comment by superkahn** [comment]
![image](https://user-images.githubusercontent.com/112466417/188333551-7db3608a-3144-46af-abf7-dcb8b25ddd3e.jpeg)

**Comment by chris1111** [comment]
Airport issue, disable WIFI in Bios for installing from USB

**Comment by chris1111** [comment]
Are you installed macOS ?

**Comment by superkahn** [comment]
I disabled wifi on bios but it's the same issue. 
![image](https://user-images.githubusercontent.com/112466417/188351257-3480511a-1df1-490e-9932-d3c976c6b679.jpeg)

**Comment by superkahn** [comment]
> Are you installed macOS ?

MacOs is basically installed but it doesn't let me go into the last step of creating a userspace with a desktop and everything else

**Comment by chris1111** [comment]
Read the page about WIFI compatibility, if the wifi card is not compatible , disable AirportBrcmFixup.kext in config.plist

**Comment by superkahn** [comment]
> Read the page about WIFI compatibility, if the wifi card is not compatible , disable AirportBrcmFixup.kext in config.plist

I did that too but same message. It's strange, I think it might be the type of usb i am using. I used another usb and it downloaded the install data but didn't finish the installation. So maybe i am guessing is i have to buy a usb that people have successfully installed Monterey on?

**Comment by superkahn** [comment]
*Update*

It seems like this is a USB issue.
This person had the same problem.

![Screen Shot 2022-09-05 at 3 19 11 PM](https://user-images.githubusercontent.com/112466417/188504640-41a15511-9247-4b3b-9642-67e3db5878f8.png)
