### ISSUE TITLE
Wifi works but it disables HP-Probook DSDT.aml and replaces it with custom DSDT.aml

### ISSUE THREAD

**Issue by superkahn** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#148]
Hi Chris.
So when this happens I lose the battery indicator, brightness, volume, etc. 
I dragged AirportItlwm.kext into the OC/kexts  folder and then I updated the config with proper tree and when I reboot the wifi works but it doesn't load from the HP package creator DSDT.aml because it creates it's own custom DSDT.aml to boot from.  
I have an Intel AC-7260 wifi/bluetooth adapter installed.
Can I merge these 2 DSDTs to make the wifi work or something similar?

I am running a probook 4540s with Monterey 12.5.1

**Comment by superkahn** [comment]
This is the custom DSDT.aml
[https://www.file.io/ct32/download/wkt9ivZBXlUH](url)

And this is the DSDT from the HP package creator
[https://file.io/UfBOMrngtDyL](url)

**Comment by chris1111** [comment]
Of course everything is patching in DSDT by the program, then wifi for Broadcom
Why open another issue here if you use an incompatible wifi card; you have the right to do this but please don't ask for help here.
