### ISSUE TITLE
Error when opening Install media HP Laptop OC

### ISSUE THREAD

**Issue by yusonious** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#15]
Greetings @chris1111 
I get an error when opening the Install media HP Laptop OC. I am running macOS Big Sur 11.0.1 on a VMware. 
The error shows in the screenshot below saying it is corrupted or damaged. 
I am trying to run macOS Big Sur on my HP Probook 6470b.
This file is in an .app format but It shows as a folder on my desktop. 
Please help me with this situation. 
Thank you.
![Screen Shot 2020-11-30 at 5 56 46 PM](https://user-images.githubusercontent.com/27751050/100691257-26afa900-333d-11eb-967b-1e445922dafe.png)

**Comment by chris1111** [comment]
not working on VM its for Mac or Hackintosh

**Comment by yusonious** [comment]
The terminal command worked. Thank you!

**Comment by chris1111** [comment]
> The terminal command worked. Thank you!

glad this is works
Let me know it the USB creation works on Virtual machine
thanks

**Comment by yusonious** [comment]
It gave me an error but I did it on my Hackintosh on High Sierra and it finished successfully. Please see my second error on the open issues.

**Comment by chris1111** [comment]
Issue is deleted 
SPAM
