### ISSUE TITLE
Erorr time out 1712

### ISSUE THREAD

**Issue by MREVO0** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#151]
I tried more than once and applied all the steps and the same case I know the graphics card but after rebooting 4 screens appear please help me
HD 4000 Pather
![٢٠٢٢٠٩١٦_٠٦٠٧٤٠](https://user-images.githubusercontent.com/113738552/190833727-cd4c995d-8af3-447d-a1d1-e2e19e540df4.jpg)
![٢٠٢٢٠٩١٧_٠٣٠٥٥٧](https://user-images.githubusercontent.com/113738552/190833722-c9d4c3f2-f4ea-4ef5-8d9d-7eba20e77c57.jpg)
![٢٠٢٢٠٩١٧_٠٣١٨٢١](https://user-images.githubusercontent.com/113738552/190833725-dba47093-e4c4-462c-9ef5-46b6dfd32896.jpg)

**Comment by chris1111** [comment]
update Monterey before applying the patch
