### ISSUE TITLE
6470b Hd4000 Monterey 12.6 brightness slider missing

### ISSUE THREAD

**Issue by mkdj77** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#155]
Hi since last 2 3 years I'm using my ProBook 6470b for my DJing/live music perfoming installed mac using your clover package creator Thank for your awesome work... @chris1111 

Currently i have Monterey 12.6 running on 6470b (i7 3520m) pre install check and testing... For moving from high Sierra to Monterey (would love get suggestion big sur or Monterey?)

Monterey is running good (nice hd 4000 patch bro @chris1111 ) so far but i don't have brightness (so far my main concern is that)
No brightness slider in sys pref. also
 Please help me get past this issue
I need Max perfomance out of my 6470b because this is the only thing i have for making music and perfoming at stage

Cpu : i7 3520m
GPU : Hd4000 (qe/ci working with hd4000 but no brightness control in sys pref and control center)

**Comment by mkdj77** [comment]
I'm not good with dsdt patching...and i tried a lot with it...
Bu I'm getting so many errors there

**Comment by mkdj77** [comment]
commented [now](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/155#issuecomment-1287235734)
Would love to know if bigsur 11.7 will have brightness with hd4000 patch on 6470b

**Comment by smscholz** [comment]
Hi
my experience with a slightly different combination: 6470b i5-3360M (HD4000) 1600x900 Monterey 12.6.1 fresh install yesterday: brightness control is working fine. 
I selected both (high-screen) patches for 1600x900 in the "Install HP-Probook-Elitebook-macOS.pkg": "Intel HD4000 for 7 Series" and "HDMI High screen", after that I run the generated "PatchHD4000" app. 
Maybe this helps, maybe not.
