### ISSUE TITLE
Error when booting Into usb

### ISSUE THREAD

**Issue by yusonious** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#16]
![1531FF4C-7B0D-4B30-B9F9-C1BAA6AFCF51](https://user-images.githubusercontent.com/27751050/100787168-dbe36f00-33d8-11eb-998b-3ed26e283549.jpeg)

I get error when booting from usb on hp probook 6470b. I booted from usb and clicked on the option to boot from macOS Big Sur 
I changed settings in bios 
Bios version is f.74

**Comment by chris1111** [comment]
This is a Impossible 
This is A SPAME issue will be delete
