### ISSUE TITLE
Elitebook 8470p Fans are not found and no wifi 

### ISSUE THREAD

**Issue by elitebookpty** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#160]
I have an elitebook 8470p. The installation for Monterey 12 worked like a breeze. but when finished mac fans control says there are no fans on the system, (of course they are there) but they are spinning way out of control incredibly noisy. Anything I can do? I selected the Smooth option when installing your package but it made no difference. Included my Efi file to see if there is any solution? thanks beforehand.

I also bought the BCM943224HMS wifi card you recommend and put the brcmfx-delay=15000 bootflag but it still doesnt work. The card was tested on windows first and it does works.

p.s. I took out the resources folder withing the OC folder because its not relevant to this issue and github wouldnt let me upload the compressed efi folder because it was more than 25mb.

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/10210316/EFI.zip)

![Screen Shot 2022-12-12 at 11 55 40 AM](https://user-images.githubusercontent.com/120405943/207113318-3ecc9bc8-cd2a-4207-a49e-831e755008c3.png)

![Screen Shot 2022-12-12 at 11 56 58 AM](https://user-images.githubusercontent.com/120405943/207113291-c6ac2b1a-9b57-4c26-b652-c4be29f52246.png)

**Comment by chris1111** [comment]
Mac Fan Control not working in Hackintosh
You have HWMonitor.app in your Applications, lets the sytem quiet a bit then open HWMonitor.app

If the Wifi card not work is probably a bad card from China

**Comment by elitebookpty** [comment]
well it does works, I tested it in Windows. So theres is no workaround to make it work? the wifi card?

**Comment by elitebookpty** [comment]
ok thanks
