### ISSUE TITLE
Eo

### ISSUE THREAD

**Issue by onoakino** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#161]
Getting this error message when trying to create USB installer. My downloaded MacOS is 12.6.3.

Couldn't mount dmg /Applications/Install macOS Monterey.app/Contents/SharedSupport/SharedSupport.dmg (error code 112)/Applications/Install macOS Monterey.app does not appear to be a valid OS installer application. (253)

**Comment by chris1111** [comment]
The installer macOS need to be on te same drive you trying the program.

**Comment by onoakino** [comment]
The error seemed to have stemmed from a corrupted macos installer download.Redownloading fixes it for me. Please close this issue. Thanks
