### ISSUE TITLE
Probook 4540s Opencore installer,intallation cannot be proceed because the installer is damaged

### ISSUE THREAD

**Issue by ostadnart** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#165]
Hello chris
I installed Big Sur by your guide on my probook 4540s 2 year ago.
My ssd hard was foramated yesterday by my fault and i tried to install Big Sur again by USB Installer that i created and used before(that USB Installer that i created by your guide 2 years ago) but on 15 min time in installation process it says Installation cannot be proceed because the installer is damaged.
What can i do to fix this problem?
Is it related to time?i means can i change the time on terminal to fix it?
If yes please say to me what time?
Or any way that you suggested
Please help chris
I have not any mac to use

**Comment by chris1111** [comment]
Yes you need change time form terminal

**Comment by ostadnart** [comment]
I tried 2021 for year,2020,2019
But same error
Last time i typed:
date 0901000021
But no lucky

**Comment by chris1111** [comment]
Sorry but I have to closed this issue because its not really relate of the program.
You can reply or any other can reply on this issue

**Comment by ostadnart** [comment]
> Sorry but I have to closed this issue because its not really relate of the program. You can reply or any other can reply on this issue

Chris you are pro in this but i'm not.
Please help me.
I redownload big sur again and have to install windows and vmware to create bootable usb again but same error.
Please wright for me the correct time and date that solve my issue.
Big sur

**Comment by arjepsen** [comment]
Did you figure out how to get past this error? I am having the same problem.
