### ISSUE TITLE
Post Install sip

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#170]
Installed Ventura, after installing EFi and reboot can't install post patch
![PXL_20230403_221049078](https://user-images.githubusercontent.com/222385/229628916-7d5c5c04-e929-4c43-b297-1a08fadf0f2d.jpg)

**Comment by peekpt** [comment]
I did tried a few times.

![PXL_20230403_225458531](https://user-images.githubusercontent.com/222385/229636304-23a86c46-c3b6-4278-a8a0-8165ad895fa9.jpg)
![PXL_20230403_225551673](https://user-images.githubusercontent.com/222385/229636312-b2ee3ed3-3578-40fa-81ac-679c33bd1290.jpg)

**Comment by peekpt** [comment]
Sorry it's a 650 g1 intel4600 core i7

**Comment by chris1111** [comment]
Your certainely not booting from the post Install SSD 
I have the same laptop

Look the config.plist
![Screenshot 2023-04-03 at 6 08 45 PM](https://user-images.githubusercontent.com/6248794/229638305-796bbbe8-3def-449d-a0ae-5a1bd2608ec9.png)

**Comment by peekpt** [comment]
Yes I am , with the EFI generated from the .PKG file
![PXL_20230403_232359988](https://user-images.githubusercontent.com/222385/229640528-30093d63-4380-4907-9d80-79ccb6262080.jpg)

**Comment by chris1111** [comment]
Your not booting from this SSD because from this SSD SIP it fully disabled

**Comment by peekpt** [comment]
I am , I also disabled verbose --v just to be sure I'm booting the right EFI, no USB inserted.
![PXL_20230403_233907122](https://user-images.githubusercontent.com/222385/229642642-496565f4-9da9-4b98-b201-e069dac2c45f.jpg)
![PXL_20230403_233924664](https://user-images.githubusercontent.com/222385/229642662-93da567f-fe6f-4c4e-8f86-33b4f8576e2a.jpg)
![PXL_20230403_234002432](https://user-images.githubusercontent.com/222385/229642684-5b30e4f3-d9a2-4ad0-a1bf-3d3799b04a02.jpg)

**Comment by chris1111** [comment]
try booting form HP USB create install install media the SIP is the same

**Comment by peekpt** [comment]
I will reinstall tomorrow then I give you feedback

**Comment by peekpt** [comment]
Fresh install , same thing. I don't know what to do! Are you using OCLP 0.6.2?
![PXL_20230404_093444427](https://user-images.githubusercontent.com/222385/229735847-d8b6b69e-7a6e-44df-8a61-f07d255ab3fc.jpg)

**Comment by peekpt** [comment]
Wait a moment...  I am using 13.3 🤨 maybe that's why, I will install 13.2.1

**Comment by peekpt** [comment]
Same thing happened, created a new USB boot disk with the 13.2.1.
What can I do?

**Comment by peekpt** [comment]
Hi @chris1111 please don't be mad at me I want to help, I'm sorry if cause discomfort:
Anyway I finally manage to  get it working.

this what I did to overcome my problems (no wifi, no battery, no post install patch):

- updated to last OC 0.9.1 and OCConfigurator for 0.91
- in ACPI one of them was disabled can't remember the one , but I enable all:
![Captura de ecrã 2023-04-07, às 12 07 09](https://user-images.githubusercontent.com/222385/230602331-bb63017a-7dc1-4d96-8d9d-554c961df8ec.png)

- This missing line was causing the sip problem in OCLP post install
![2](https://user-images.githubusercontent.com/222385/230603946-0ccffd91-bf4b-4f80-b249-b0ac3182d304.png)

- updated all drivers for OC 0.9.1 
![3](https://user-images.githubusercontent.com/222385/230604350-41371a69-281f-4577-b553-dde25ffe6c0e.png)

- ECEnabler was missing in order to get battery working. My intel card is working with this driver. Both methods work, one uses Airportdriver  the other creates a ethernet connection bridge and you need Heliport app to mimic the status icon.
![Captura de ecrã 2023-04-07, às 12 08 04](https://user-images.githubusercontent.com/222385/230602968-d4897a0f-0425-4bd2-b119-c0d3ab71c82f.png)


I hope this helps!

**Comment by chris1111** [comment]
I will add delete `csr-active-config` It won't change much but I don't have a problem with it.

**Comment by peekpt** [comment]
@chris1111 Just to let you know that VoodoPs2Controller 2.3.5 it's working fine! I have full gestures now, don't need 1.9.2 anymore!

**Comment by peekpt** [comment]
0.6.3 release intel fixed graphics on maps, imageviewer , etc...
