### ISSUE TITLE
Elitebook 8470p New install Ventura 13.3 - No Bluetooth

### ISSUE THREAD

**Issue by elitebookpty** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#171]
Before I had Monterey and the wifi was not working ( I have a BCM943224HMS which supposedly was compatible with Monterey but no go. Bluetooth would work fine). Now using the new tools from your github I installed Ventura, everything is working awesome, but now I do have Wifi but no Bluetooth.

![image](https://user-images.githubusercontent.com/120405943/229683513-a183eb80-ca55-49cc-9107-4272c74648e7.png)

 
![image](https://user-images.githubusercontent.com/120405943/229683040-044bdf10-a7ce-4d06-a4e0-598a58cbf033.png)

Any ideas on how to fix the bluetooth? I installed exactly as you showed in the videos. 

I include my EFI to see if theres anything I could change to get the bluetooth working?
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11144490/EFI.zip)

**Comment by chris1111** [comment]
I know its same for me I disable the card Bluetooth in bios then I use a dongle compatible for now 

![scree785](https://user-images.githubusercontent.com/6248794/229744827-ef831a06-85ff-401f-8fdd-49fc9e7c65c1.png)

**Comment by chris1111** [comment]
[Bug Fix ](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/commit/1ab20797cd8a56705d033a3bdbd86dd8d3201c7e)
Add this kext then Enable it.
Reactivate Bluetooth in bios then unplug dongle USB Bluethoot

[BrcmFirmwareData.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11227225/BrcmFirmwareData.kext.zip)
