### ISSUE TITLE
hp probook 450g1 Ventura 13.2.1 clean installation 

### ISSUE THREAD

**Issue by cippo57** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#173]
Hi Chris1111,
Beginner help me pls. 
During installation mac Ventura, using your last update,  en error occurring 
![IMG-20230404-WA0002_edit_650120215404965](https://user-images.githubusercontent.com/83537380/230641842-e4717c0c-0d78-40b1-83cb-b62f5916f6df.jpg)

**Comment by cippo57** [comment]
Install MAC OS VENTURA USB was from VM 17

**Comment by chris1111** [comment]
I dont trust VM, 
i just test 5 minutes a go an install on spare SSD of 13.2.1 without issue

**Comment by cippo57** [comment]
Ok Chris
I will check again
Happy Easter to you

**Comment by chris1111** [comment]
> Ok Chris I will check again Happy Easter to you

Happy Easter to you to and your familly ![HappyEaster](https://user-images.githubusercontent.com/6248794/230721161-d09dcfeb-ca35-413e-b7f4-80576ba159fe.png)

**Comment by chris1111** [comment]
Try to plug the Eternel cable ?

**Comment by cippo57** [comment]
Thank you Chris, Same problem with ETH cable 
PLS, have a look on file attached , may help you ?
[ia.log](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11209143/ia.log)

**Comment by chris1111** [comment]
> Thank you Chris, Same problem with ETH cable PLS, have a look on file attached , may help you ? [ia.log](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11209143/ia.log)

Not really

**Comment by cippo57** [comment]
Sorry for that...
Any other suggestion, PLS, ?
I don't have   any mac  available to build installer and check...
THANK YOU

Cipriano Molfese
cell 329 4950402
***@***.***

Il mer 12 apr 2023, 11:55 chris1111 ***@***.***> ha scritto:
