### ISSUE TITLE
Help please..

### ISSUE THREAD

**Issue by danielaki** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#176]
Hello Chris, thank you very much for this big project! After many attempts, I was able to install Ventura on my old HP ProBook 6470b laptop. My question is: I have an i7-3720QM, but the information displayed shows that I have an i5. Can this affect my performance? If so, how can I make it recognize my i7? Thank you very much.

![Captura de Tela 2023-05-09 às 12 32 05](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/126002925/acd3e198-bdc9-4575-b6e8-1ecd0a590433)

**Comment by chris1111** [comment]
do you have a High Screen 1600x900?

**Comment by danielaki** [comment]
> do you have a High Screen 1600x900? Witch macOS you have installed?

Ventura. 1366x768

**Comment by chris1111** [comment]
You can try [CpuFreind](https://github.com/acidanthera/CPUFriend) ensted of SSDT gen for turbo boost

**Comment by chris1111** [comment]
Try to buying a compatible Wifi it would be worth it considering that now it's no longer a laptop stored in a cupboard

**Comment by danielaki** [comment]
> Try to buying a compatible Wifi it would be worth it considering that now it's no longer a laptop stored in a cupboard


I don't use wifi/bluetooth. I tried to follow the steps, if I understood correctly I needed to do this. But not work.

![Captura de Tela 2023-05-09 às 16 36 06](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/126002925/4cfd569a-4369-4eb5-829d-736e7e8a7e0f)

**Comment by chris1111** [comment]
sorry but I'm not here to find all the solutions to the requests, considering that the work is done by the program at 100%
For the rest try to find your solutions by carrying out your tests, then when you have found come and post the solution which will be useful to others, I have more than 6 series laptop so for me it is not very useful but for others yes

**Comment by danielaki** [comment]
> sorry but I'm not here to find all the solutions to the requests, considering that the work is done by the program at 100% For the rest try to find your solutions by carrying out your tests, then when you have found come and post the solution which will be useful to others, I dont have anymore a 6 series laptop so for me it is not very useful but for others yes

in monterey the turbo boost was working. Unfortunately I don't have the knowledge to solve it, I've already researched and most of the content for the 6470b is very old... if i find the solution i'll come back here. Tks.

**Comment by chris1111** [comment]
If it work on Monterey it probably work in Ventura

**Comment by chris1111** [comment]
For my part, Wifi and blutooth are much more important on a Laptop than the turbo boost given that your CPU is very powerful anyway; it changes practically nothing to the work you do

**Comment by danielaki** [comment]
> For my part, Wifi and blutooth are much more important on a Laptop than the turbo boost given that your CPU is very powerful anyway; it changes practically nothing to the work you do

I'm go testing for a one week, but I can see that it's much slower than monterey. maybe i'm go back to him myself. Thank you very much! :)

**Comment by danielaki** [comment]
Hello Chris, I found a solution to fix the turbo on the ivy bridge in the ventura. It looks like binaries have been removed on ventura
[Fix Turbo-Ivy.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11453373/Fix.Turbo-Ivy.zip)
.

All I need to do is replace the files with these and add the two kerts to the config.plist

My other problem to build patcher to update ventura 13.3.1 (a) (is safe?): "xcodebuild -project ./HP-ProBook-EliteBook.xcodeproj -alltargets -configuration Release
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance". How fix this? thanks..

**Comment by chris1111** [comment]
Install command Line Tools

**Comment by chris1111** [comment]
You can build just drag Main.sh to the terminal following by enter

**Comment by chris1111** [comment]
> Hello Chris, I found a solution to fix the turbo on the ivy bridge in the ventura. It looks like binaries have been removed on ventura [Fix Turbo-Ivy.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11453373/Fix.Turbo-Ivy.zip) .
> 
> All I need to do is replace the files with these and add the two kerts to the config.plist
> 
> My other problem to build patcher to update ventura 13.3.1 (a) (is safe?): "xcodebuild -project ./HP-ProBook-EliteBook.xcodeproj -alltargets -configuration Release xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance". How fix this? thanks..

update ventura 13.3.1 (a) not working on 6 series laptop
