### ISSUE TITLE
BT dead again

### ISSUE THREAD

**Issue by ruler666** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#177]
Hi Chris,

I successfully updated my Monterey installation to Ventura when you published new code for Ventura installation. And finally my BT started to work without the need of 'warm reboot' which was preserving loaded firmware, so I was able to use it in Ventura. 

Then I started playing around with it (wanted to fix the problem of some apps not opening like Whatsapp) and when I failed to fix it I decided to revert back to the backed up EFI I had from the original, working installation.

Now everything's back to normal, except BT. It doesn't work at all. I bought AzureWave card (WIFI + BT Combo) you recommended on the your project page  on github.

Also just to mention I have 7-series laptop (4x40s).

I will attach my EFI here to see if you can make any sense of this and figure out what I did wrong. Any help is highly appreciated!

Thanks!

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/11455924/EFI.zip)

**Comment by chris1111** [comment]
I not need your attach EFI I just Update bluetooth kexts yesterday then I have the same Wifi card and its work

First of all the Ventura support page not talk about updated Monterey to Ventura but installing Ventura 13

**Comment by ruler666** [comment]
I do understand that it works. It did work for me too. I screwed something up so I thought maybe you have some advice. But ok, I'll figure it out on my own.

And BTW I successfully upgraded from Monterey, so in case someone is searching, I just want to state that I managed to upgrade from Monterey to Ventura with not many issues.

Thanks!

**Comment by peekpt** [comment]
@chris1111 workaround for BluetoothFixUp.Kext  on ventura 13.4

add to NVRAM>7C436110-AB2A-4BBB-A880-FE41995C9F82
bluetoothInternalControllerInfo 00000000 00000000 00000000 0000 (DATA)
bluetoothExternalDongleFailed 00 (DATA)
