### ISSUE TITLE
Black screen on Elitebook 2570p 

### ISSUE THREAD

**Issue by Biodegradavide** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#18]
I've followed the video guide, but even if I boot directly from the bootx64.efi, i have a black screen. I've tried to use the debug and the boot stops at Watchdog status is 0. Thanks for the help.
![IMG_20201208_142302](https://user-images.githubusercontent.com/61192921/101489928-ef0ab780-3961-11eb-8002-300ef0249b47.jpg)
[opencore-2020-12-08-142507.txt](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5659510/opencore-2020-12-08-142507.txt)

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/2#issuecomment-679373248

**Comment by Biodegradavide** [comment]
Thanks, i will try it

**Comment by Biodegradavide** [comment]
Still not working even with the edit. My laptop has a 1366x768 screen

**Comment by chris1111** [comment]
If your laptop as 1366x768 screen not need this procedure
Follow the exact guide 2570p already test and works

**Comment by Biodegradavide** [comment]
Are:
Default setup
Disable LAN/WLAN Switching
UEFI Hybrid with CSM
Disable FastBoot
the only things to change in the bios?

**Comment by Biodegradavide** [comment]
Sorry for the question, but in the video you have to be sure that there isn't DSDT.aml in ACPI folder; but the text guide says: "Create Install Media HP Laptop tools « IMPORTANT » without any file aml (DSDT.aml), (SSDT.aml) in /EFI / OC / ACPI". Which is more relatable?

**Comment by chris1111** [comment]
follow the guide

**Comment by Biodegradavide** [comment]
> follow the guide

Which guide, the video one or the other one?

**Comment by chris1111** [comment]
> > follow the guide
> 
> Which guide, the video one or the other one?


https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC

**Comment by chris1111** [comment]
See ➤ [Confirmation 2570p](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC#bios-version)

**Comment by Biodegradavide** [comment]
Sorry, but I have the last question; the guide says "Create Install Media HP Laptop tools « IMPORTANT » without any file aml (DSDT.aml), (SSDT.aml) in /EFI / OC / ACPI". Does this mean that I have to delete all the files on the ACPI folder in the bootable USB?

**Comment by chris1111** [comment]
Installer install necessary file

**Comment by chris1111** [comment]
are you trying to find a black spot to have a few things to say
