### ISSUE TITLE
Mojave with OC?

### ISSUE THREAD

**Issue by sacheats** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#181]
Hello chrish, all my attempts to get OC to work with Mojave have failed. After the first install reboot, the macOS unit no longer appears. I was able to test with Clover and it worked, but not with OC. Can you help me? (hp 6470b)

**Comment by chris1111** [comment]
Setup APFS  /UEFI / MinVersion
![Screenshot 2023-08-04 at 06 38 47](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/b5ec323a-111c-49bf-ae35-e6c34aff9e07)

**Comment by sacheats** [comment]
@chris1111 hello chris, same problem check
![04111651](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/2260728a-d7d9-4f04-a2dc-0a4f23f88719)
![Captura de Tela 2023-08-04 às 8 22 10 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/278d2e4f-07c5-4d33-8587-43f7b32f0bb4)

**Comment by chris1111** [comment]
Your not using latest program

**Comment by sacheats** [comment]
> Your not using latest program

@chris1111 same
![Captura de Tela 2023-08-04 às 8 44 48 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/ffa3b8a6-c982-4644-9631-c5ae7c82ec9b)
![04113622](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/a4b949d6-5bb0-46a7-b7da-69cdb27ffd96)

**Comment by chris1111** [comment]
Your laptop need VBoxHFS

**Comment by sacheats** [comment]
> Your laptop need VBoxHFS

@chris1111 same, 
![04115315](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/d76f8e0a-7e8d-4260-9937-fdd9ac04e3d0)


![Captura de Tela 2023-08-04 às 8 55 23 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/77c4c3a4-90ed-490b-a7b2-ff18d2b66fa9)

**Comment by sacheats** [comment]
> Stop to mixed issue then O C as nothing to do here clear NVram + TAB Reboot

@chris1111 same error
![04121111](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/932c26d0-6ae5-454d-92f9-11050703e305)

**Comment by chris1111** [comment]
So it is Bios version or Setup

**Comment by sacheats** [comment]
> So it is Bios version or Setup

@chris1111  clevo works, bios is f74 rev a. OC worked for me in big sur, monterey, ventura and if I'm not mistaken I tested Catalina with OC. I am not sure.

**Comment by sacheats** [comment]
@chris1111 it worked for catalina. have kext for wifi 62205anhmw or no compatible?

**Comment by sacheats** [comment]
@chris1111 Hi chris, I'm on mojave with clevor, on OC I can put a SMBIOS to avoid upgrade updates, ex: from catalina to big sur. But in Clevor when I remove the SMBIOS from 12.1 (last update monterey) to 9.1 or 9.2 it doesn't work anymore, I have a kernel panic... is there a solution?

**Comment by sacheats** [comment]
> @chris1111 Hi chris, I'm on mojave with clevor, on OC I can put a SMBIOS to avoid upgrade updates, ex: from catalina to big sur. But in Clevor when I remove the SMBIOS from 12.1 (last update monterey) to 9.1 or 9.2 it doesn't work anymore, I have a kernel panic... is there a solution?

i found a solution for that, my other question is about bluetooth, it worked on catalina, big sur, etc... but not on mojave, how can i fix it?

**Comment by chris1111** [comment]
Replace BrcmPatchRAM3.kext by `BrcmPatchRAM2.kext`
BrcmPatchRAM2.kext: for 10.11 - 10.14.
[BrcmPatchRAM2.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12266783/BrcmPatchRAM2.kext.zip)

**Comment by chris1111** [comment]
Or if you boot several macOS with the same EFI you can indicate Min and MaxKernel to your kexts and leave both kexts

![Screenshot 2023-08-05 at 06 22 29](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/0c1be21b-b1df-4b82-b1e3-449352248cfe)

**Comment by chris1111** [comment]
![Screenshot 2023-08-05 at 06 30 58](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/3a36c2b8-edfb-4b97-9836-bbb70d495c11)

**Comment by sacheats** [comment]
@chris1111 I put this kext but bluetooth did not activate in mojave, in fact I don't even see the bluetooth function in the system preferences panel 
![Captura de Tela 2023-08-05 às 11 40 05 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/ac094308-931c-479c-8849-b1a52f86248b)
