### ISSUE TITLE
After first installer the install drive doesn't show.

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#183]
Hi friend, I have tried few time but its seems consistent issue. After booting from USB and installer load some files to SSD and then it reboots and that SSD disappear. I tried use HFS partition then it shows the drive and after 2nd boot installer continues, but then after 2nd reboot it again disappear. It seems the USB only able to show the HFS drives but not APFS. Since it convert back to APFS during installation, I think may be that's why it's not showing. I third both Mojave and Catalina both have the issue. But rest of others versions, its good. 

Can you please guide what I should do? Thanks

**Comment by Mtkhan13** [comment]
I have also tried vBoxHFS as well but same issue.

**Comment by chris1111** [comment]
I dont have issue with Catalina latest Program update config.plist with this
This way you dont have anny APFS restriction

![Screenshot 2023-08-09 at 17 15 55](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/5d8b8033-faa2-4ac9-a0fd-72b78b95a777)

**Comment by Mtkhan13** [comment]
![Screenshot 2023-08-10 at 2 20 35 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/910494e8-e39a-4e73-a508-efa2be1fac91)
Ah I see now it my installer its 0 0

**Comment by Mtkhan13** [comment]
Awesome I change it to -1 and it worked.  Thanks

**Comment by Mtkhan13** [comment]
Please see the code I think this part is missing because I didn't change the plist after creating the installer. 
But Thanks again !

**Comment by chris1111** [comment]
> Please see the code I think this part is missing because I didn't change the plist after creating the installer. But Thanks again !

No its there [See commit](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/blob/master/Builder/Create-Install-Media/V-BOX/EFI/OC/config.plist)

![Screenshot 2023-08-09 at 17 31 42](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/24082d8a-fdfc-435f-9536-b5ef49beb0d7)

**Comment by Mtkhan13** [comment]
Yes you are right but somehow it's not working on Mojave and Catalina as I'm using the latest release of yours. And for proof I'm also attaching a video post installation as it didn't add the -1 in the plist. Somehow it's working on later OS versions but not on Mojave and Catalina. I've to reinstall the OS because after reboot the MacOS drive did't work and even the usb with -1 couldn't pickup the drive. 

Please see https://drive.google.com/file/d/1-urCdwoAMwDyOZWNQDtg47R3VPyClY0Y/view?usp=share_link

**Comment by Mtkhan13** [comment]
![Screenshot 2023-08-10 at 3 54 24 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/bba76250-5e63-4109-8577-2c160d16e677)
