### ISSUE TITLE
BCM94352HMB not working on Sonoma

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#184]
Hi Chris,
HP 4440s running Sonoma very well but WiFi is not working. It is activated but does not detect any network. Even BT is working.
I have not changed anything from config.plist but platform info.
Any clue?
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12343011/config.plist.zip)
![Captura de pantalla 2023-08-15 a las 11 41 56](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/69108535/25ec4e0d-6125-4bca-8bb4-848020605baa)

**Comment by chris1111** [comment]
Send complete EFI on Zip I will see

**Comment by antoniojveraa** [comment]
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12343189/EFI.zip)
I deleted Resourse folder to be able to attach the file.
Tks.

**Comment by chris1111** [comment]
Will see when back home tonight's

**Comment by antoniojveraa** [comment]
I appreciate it.
It was working fine on big sur, also using your apps, and yesterday I decided to gave a try to Sonoma. Actually I clean installed it twice an everything works but WiFi.
By the way, I don't mind to loose my PC data so I could be a tester if you ever need one in Spain. My wife and I have this 4440s i3 and another HP 250 i5 7th.

Regards,

Antonio

________________________________

**Comment by chris1111** [comment]
Check this setup to find network 
![260679995-25ec4e0d-6125-4bca-8bb4-848020605baa](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/8c3c27bc-faff-494b-a282-de6ab26737a5)


or reinstall OCLP

You are suppose to be to see this on OCLP
![capt1668](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/777001a4-4d80-4394-8b7a-93d1925eef00)

**Comment by antoniojveraa** [comment]
Good morning/evening Chris,

I reinstall OCLPn as you said but I don’t have the option you pointed at:
￼￼￼￼
I’m going to work in a couple of minutes. When I come back home I will do some testing re-ordering the .kext.

Tus,

AV

**Comment by chris1111** [comment]
Try Reinstall macOS from scratch because it suppose to be working, I have done succesfully multiple test also two os my best tester.

**Comment by antoniojveraa** [comment]
I already install macOS twice from scratch. Actually, I did it the second time because of the WiFi problem with same results.
Thanks anyway.
I let you know if I find the problem without reinstalling everything again.

Regards,

Antonio

________________________________

**Comment by chris1111** [comment]
It Fix Now Follow every steps  
Download OCLP again

![Screenshot 2023-08-16 at 11 16 11 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/48a25170-29d7-453e-99f2-386cd4662035)

**Comment by antoniojveraa** [comment]
Hi Chris,

Thanks for let me know it!!!
Yesterday I downloaded Ventura and installed it with same results, no wifi but this time I wasn't able to activated it.
When I come back from work I will do what you said.

Thanks!!!

Tony

________________________________

**Comment by chris1111** [comment]
![Screenshot 2023-08-17 at 5 36 18 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/0b0a5ab3-f53b-427e-aaef-a059ef3ef0cf)

**Comment by antoniojveraa** [comment]
Hi Chris,

After downloading Sonoma.app again and create media, etc. etc. This is the result, basically I can not turn on the WiFi card:
I give up and go back to Monterrey.
I'll keep reading you at GitHub and test newer versions of your installer.

Regards,

Tony
________________________________
De: chris1111 ***@***.***>
Enviado: jueves, 17 de agosto de 2023 11:38
Para: chris1111/HP-Probook-EliteBook-Package-Creator-OC ***@***.***>
Cc: Antonio Vera ***@***.***>; Author ***@***.***>
Asunto: Re: [chris1111/HP-Probook-EliteBook-Package-Creator-OC] BCM94352HMB not working on Sonoma (Issue #184)


[Screenshot 2023-08-17 at 5 36 18 AM]<https://user-images.githubusercontent.com/6248794/261268369-0b0a5ab3-f53b-427e-aaef-a059ef3ef0cf.png>

**Comment by antoniojveraa** [comment]
Hi again Chris,

I had two weeks without booting into Windows and I did it today and realized that I had no WiFi. Somehow the card was disable but I don't even know how to do this even if I wanted to.
Anyway, I enabled the card in Windows and boot into macOS and now I have WiFi.
Thanks for your help!!!

Tony
________________________________
De: Antonio Vera ***@***.***>
Enviado: jueves, 17 de agosto de 2023 19:23
Para: chris1111/HP-Probook-EliteBook-Package-Creator-OC ***@***.***>
Asunto: RE: [chris1111/HP-Probook-EliteBook-Package-Creator-OC] BCM94352HMB not working on Sonoma (Issue #184)

Hi Chris,

After downloading Sonoma.app again and create media, etc. etc. This is the result, basically I can not turn on the WiFi card:
I give up and go back to Monterrey.
I'll keep reading you at GitHub and test newer versions of your installer.

Regards,

Tony
________________________________
De: chris1111 ***@***.***>
Enviado: jueves, 17 de agosto de 2023 11:38
Para: chris1111/HP-Probook-EliteBook-Package-Creator-OC ***@***.***>
Cc: Antonio Vera ***@***.***>; Author ***@***.***>
Asunto: Re: [chris1111/HP-Probook-EliteBook-Package-Creator-OC] BCM94352HMB not working on Sonoma (Issue #184)


[Screenshot 2023-08-17 at 5 36 18 AM]<https://user-images.githubusercontent.com/6248794/261268369-0b0a5ab3-f53b-427e-aaef-a059ef3ef0cf.png>
