### ISSUE TITLE
PatchHD4000 or OCLP

### ISSUE THREAD

**Issue by sacheats** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#186]
hello @chris1111, what is better to Monterey? Have diference on performance?

**Comment by chris1111** [comment]
No differance but if you can not using a software dedicated for Real Mac it makes sense to avoid for a Hackintosh

**Comment by sacheats** [comment]
@chris1111 i installed the patchHD4000 but not showing texts on safari
![Captura de Tela 2023-08-26 às 10 11 55 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/21047444/d2c00c9c-d182-43b5-a6e1-7c8aec6db38b)

**Comment by chris1111** [comment]
[Fix Safari HD 4000 Monterey](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/tree/master/Builder/HPProBookEliteBookmacOS/PatchHD4000)
