### ISSUE TITLE
Support Hp Probook 450 G1 (4.Gen haswell)

### ISSUE THREAD

**Issue by ramyhq** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#187]
hi, 
I hope you have a great day.
Kindly let to know if there is support for the HP Probook 450 G1
CPU: 4200M
GPU Intel 4600

I want to install (Ventura 13 or Sonoma 14)

Please if you can help me in any way please contact me 
ramy.dmk@gmail.com

Thank You in Advanced

**Comment by chris1111** [comment]
Program support 4x0G1 for long time a go

![Screenshot 2023-08-26 at 22 51 30](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/bc7cffc8-a8f2-4ed1-b108-3a7458c7c4e6)

**Comment by ramyhq** [comment]
That's Greate news for me 
Thank you so much

**Comment by chris1111** [comment]
> That's Greate news for me Thank you so much

For Ventura follow every step in Video because I have 650 G1 so the only diferance is you selected 4X0G1
