### ISSUE TITLE
turbo boost ssdtgen + bluetooth = panic

### ISSUE THREAD

**Issue by sacheats** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#188]
hello @chris1111 , i tested a Catalina + bluetooth, if bluetoothes kext is enabled with sdtPRGen panic occurs! if disable bluetooth or ssdt works fine!

**Comment by chris1111** [comment]
SsdtPrgen is not part of the program so issue is from SsdtPrgen not from Bluetooth
