### ISSUE TITLE
ProBook 6470b | Big Sur performance issue

### ISSUE THREAD

**Issue by wajwuz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#189]
Hi, recently I switched from Monterey to Big Sur and after post install my cpu name switched from i5 to i7 (before the name change it worked smoothly) and now it have performance issues. Here's some screens, if you want config.plist I'm gonna upload it somewhere.

![Screen Shot 2023-09-03 at 05 12 11](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/75165095/758ad8e5-e14d-4e71-92ef-7280dcef6b0e)
![Screen Shot 2023-09-03 at 05 13 09](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/75165095/5734a814-6d47-416f-963f-3edddf4ef948)

**Comment by chris1111** [comment]
this is only cosmetic then no issue performance about that
