### ISSUE TITLE
success! and one question

### ISSUE THREAD

**Issue by BeholdersEye** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#190]
Greetings, chris1111

I have successfully used your package creator to installed MacOS Monterey on an HP Probook 4540s and everything I intend to use seems to be working. My thanks.

I just wonder if there is any way to set the Probook's display to its native resolution of 1366x768? Currently the only option is 1024x768, which looks sharp in the screenshot but is rather "fuzzy" when stretched out on the display.
![screenshot](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/13533723/28966c7c-92dd-465c-b8ec-12e8a4e89a0d)

If not maybe there is a way to center it on the display instead of stretching it?

Thanks again for your time and efforts making this package creator.

**Edit to add:** I did try searching for the solution myself but there are so many search results for adding a _scaled_ resolution it is difficult to find the way to just add a regular old resolution.

**Comment by chris1111** [comment]
See Show All Resolution ?
![265289334-28966c7c-92dd-465c-b8ec-12e8a4e89a0d](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/8ed5527b-489c-44ed-a51e-7f6c9fcece36)

**Comment by BeholdersEye** [comment]
Ha, that doesn't work, I tried that before bothering you. Same with that magic key to hold and identify displays. ;)

Probably it is some mistake I made during install. I will try again next week.

I only wrote to ask if it is *possible* to make display in native resolution so I could tell whether:

* it was something I could fix (like changing the audio id to 13 to fix sound) 

* it was something that will never work no matter what.

If you say it can display in 1366x768 I believe you and I am happy to hear it. I will keep trying until I get it to work.

Thank you again for this fine package creator.

**Comment by chris1111** [comment]
maybe the patch HD4000 is not installed correctly ? Retry to install the patch

**Comment by BeholdersEye** [comment]
It is possible the HD4000 is not installed correctly.  I followed the video instructions but the post installer does not check the box for hd4000 patch. However, the info in About this Mac says "Intel HD 4000 graphics" if that means anything.

When I tried to run the post-install setup to install the HD4000 it gave an error, which I thought might have been because you say "ONLY install on a FRESH macOS install" which would make it forbidden to ever _re_install.

So I deleted the macOS partition. I will make a fresh macOS install and try again, installing Intel HD 4000 graphics. Expect success since as I said I will keep trying until it works. :)

See my edit above about RDM.

Also a question: When you say run the post-install setup only on a fresh install, do you mean immediately on the first reboot after install or would you rather reboot once more after that and then do a clean restart before running the post-install setup?

**Comment by chris1111** [comment]
Use the update  [patch here](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/blob/master/Builder/HPProBookEliteBookmacOS/PatchHD4000/PatchHD4000.zip)
