### ISSUE TITLE
Wifi working but Airdrop not working

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#192]
Hi Chris, i'm using BCM943224HMS seems wifi working fine but I can't find or share files using AirDrop. No other Hackintosh are showing either in the AirDrop. When I looked into System Information its showing AirPort Utility:	Not Installed
![Screenshot 2023-09-09 at 10 52 36 AM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/44416f0f-0e6f-4409-823d-3e5a8ba38774)

Please guide how to fix it. 
Thanks!

**Comment by Mtkhan13** [comment]
I had installed the card after the OS has been installed as it was in shipment from Aliexpress.

**Comment by chris1111** [comment]
Send your EFI file in ZIP if you only used my program, if this is not the case, don't waste your time.

**Comment by Mtkhan13** [comment]
No friend I didn't use any other tool just your installer. Though as I mentioned I didn't have the wifi card at first to I had installed the mac without Broadcom patch. Later when I got the card I have reinstalled the post installation with broadcom fixes. But then I feel it no longer working I mounted the drive on another system and checked the EFI folder, it seems there were duplicate entires somehow. So I have remove all the files from EFI drive and booted with usb installer into OS and then reinstall the post installer. Now its seems worked but air-drop issue and I'm also experiencing issues using photoshop as it takes ages to safe files. I'm attaching the EFI folder so you can check. 

If you think the post installer only can work best at first install then I will have to reinstall the OS from scratch. What do you suggest? I'm using Catalina and my Elitebook is 8470p. 

https://drive.google.com/file/d/1pEz2YQFZsNEvskTddW1gkS3YTT58RJ9A/view?usp=sharing

![WhatsApp Image 2023-09-10 at 7 43 44 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/3e5eeec0-9451-4d60-8bb9-94a94ea5fabd)

And one more thing please confirm as It have i5 processor I'm planning to upgrade with i7 processor. Do you think the installer will work with that upgrade automatically? if not then I will plan to buy another laptop with different model.

**Comment by Mtkhan13** [comment]
![Screenshot 2023-09-10 at 7 51 40 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/be0a8908-e485-4eff-9314-088e9102c778)

It's showing i7 but it have i5 processor. But you can see the OS is Catalina. 10.15

**Comment by chris1111** [comment]
For your AirDrop problem you do not have to install the Bluetooth kexts, here is the config.plist to modify for this purpose and the kexts to add in the EFI/OC/kexts folder

[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12568520/config.plist.zip)
[kexts.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12568521/kexts.zip)

For the Upgrade CPU you can change the CPU then reboot in macOS and it should work, no need to reinstall

**Comment by Mtkhan13** [comment]
Thats great, Thank you so much!
Let me replace it and check.

**Comment by chris1111** [comment]
Make sur Bluetooth is activate in Bios because the Wifi BCM943224HMS dont have integrate Bluetooth

**Comment by Mtkhan13** [comment]
Sure

**Comment by Mtkhan13** [comment]
![WhatsApp Image 2023-09-10 at 8 21 42 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/75f8d45c-dd9e-4122-8eb1-f1691608bdb7)
The bluetooth is active in Bios already. Do you want me to disable it in Bios?

and it still not showing any Air-Drop users. 
![WhatsApp Image 2023-09-10 at 8 23 24 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/4c368838-8198-405b-8eed-74d4006e7c5f)
![WhatsApp Image 2023-09-10 at 8 23 35 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/4de6e574-76b7-44e2-b620-976a4d5a89fb)


I have a USB bluetooth dongle you think it is usable in any case? or should I leave it. Though it is working with bluetooth devices. 
![WhatsApp Image 2023-09-10 at 8 26 03 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/b2506f6d-d81c-4723-9eff-6fdcc9f55025)
![Screenshot 2023-09-10 at 8 25 11 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/5b1c6fe8-63a8-41fe-a7d1-5b8802d44d5e)
![Screenshot 2023-09-10 at 8 25 23 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/b9f33784-dcb7-4511-bcea-4e93d699f977)

**Comment by Mtkhan13** [comment]
I have also tried with disabling the embedded bluetooth device in Bios but no luck with Air-Drop.

Here is the current structure and kext as per your shared files. 
![Screenshot 2023-09-10 at 8 43 52 PM](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/22547975/bda3a3b0-5bfb-4af5-835a-75261bd4bdcc)

**Comment by Mtkhan13** [comment]
any suggestions friend?

**Comment by chris1111** [comment]
Are you login to apple account?

**Comment by Mtkhan13** [comment]
Not at the moment --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/10/23, 9:30 PM chris1111 ***@***.***> wrote:

   
  Are you login to apple account?

**Comment by chris1111** [comment]
You need to connect to Apple for all 
Message, AirDrop, Continuty and Facetime

**Comment by Mtkhan13** [comment]
Okay, I will do that but other Hackintosh are working fine with out login apple ID --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/10/23, 10:04 PM chris1111 ***@***.***> wrote:

   
  You need to connect to Apple for all Message, AirDrop, Continuty and Facetime

**Comment by chris1111** [comment]
No way you can use Apple Services without being connected

**Comment by Mtkhan13** [comment]
Right l will connect and update you for sure. Thanks again for the help!--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/10/23, 10:11 PM chris1111 ***@***.***> wrote:

   
  No way you can use Apple Services without being connected

**Comment by Mtkhan13** [comment]
Hi Chris, I logged in to apple id but still no luck with AirDrop.

**Comment by Mtkhan13** [comment]
I've also reinstalled the OS and AirDrop not working

**Comment by chris1111** [comment]
It work here without issue with a [AzureWave WLAN+BT BCM94352HMB](https://www.ebay.fr/itm/Azurewave-AW-CE123H-Broadcom-BCM94352-802-11ac-WiFi-card-Bluetooth-4-0-for-MAC-/272248789669)
For you if you use this card, you only need to disabled Bluetooth in Bios then of course install Wifi Option  and Bluetooth kext from the program
On my 650 G1 I dont have Integrate Bluetooth so its enable from the Wifi card
![1](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/6248794/92a2d125-b5f4-4766-b539-7941b6f85cc6)

**Comment by chris1111** [comment]
Last Post [edit here](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/192#issuecomment-1713028895)

**Comment by Mtkhan13** [comment]
But you have a different card ([AzureWave WLAN+BT BCM94352HMB](https://www.ebay.fr/itm/Azurewave-AW-CE123H-Broadcom-BCM94352-802-11ac-WiFi-card-Bluetooth-4-0-for-MAC-/272248789669))
Mine is BCM943224HMS which I bought as per your guide. :)

**Comment by chris1111** [comment]
You should have taken the one I have

**Comment by Mtkhan13** [comment]
I see, okay I will buy that one. --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/13/23, 7:00 AM chris1111 ***@***.***> wrote:

   
  You should have taken the one I have
