### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by wajwuz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#194]
Hi, do you use maybe telegram or something like that so it would help me to reach you out.

**Comment by chris1111** [comment]
my email is in my profile but questions about this program its here to discus

**Comment by wajwuz** [comment]
Because on Big Sur I have issue after second install "apple logo installation" system reboots on hops into bootloop on some kexts. I can't figure out which one cuz it's too fast

**Comment by chris1111** [comment]
what wifi card do you have

**Comment by wajwuz** [comment]
intel centrino advanced-n 6205
![image](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/75165095/2aa38eff-0ccb-4691-94dd-aefb516b4185)

**Comment by chris1111** [comment]
If you use Intel Wifi kext [read carefully about](https://github.com/OpenIntelWireless/itlwm)

Anyway why not using a [Broadcom Wifi compatible](https://www.ebay.fr/itm/Azurewave-AW-CE123H-Broadcom-BCM94352-802-11ac-WiFi-card-Bluetooth-4-0-for-MAC-/272248789669) with this program and all macOS support version

**Comment by wajwuz** [comment]
well I can’t boot to os after install, can’t reach desktop after last install ste

**Comment by chris1111** [comment]
Follow the guide correctly

**Comment by chris1111** [comment]
It is not stock let it finish that's it this is normal depends the speed of USB drive then the install Disk

**Comment by wajwuz** [comment]
installed fresh and post install is done and theres a big performance issue

video https://media.discordapp.net/attachments/1129750546262261803/1151542418219466902/IMG_0311.mov
