### ISSUE TITLE
Support for HP Probook 650 G2

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#196]
Can I use this package creator on HP Probook 650 G2. It is shipped with intel core i5 6th generation.

By the way I have [repo](https://github.com/afzl-wtu/Hp-ProBook-650-G2-OpenCore-EFI) for it if it may helpfull?

**Comment by chris1111** [comment]
Its not about DSDT but DSDT patcher (Broadwell and Higher) ; patch is not availlable they were never created by anyone after the Haswell patches
See DSDT-Patch in the repos
