### ISSUE TITLE
Battery and audio doesn't work on HP 4540s

### ISSUE THREAD

**Issue by TrickyTrix** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#197]
I installed Monterey 12.7 on HP 4540s (i7-3610QM, 8GB RAM) and patched it with post-installer, but I still don't have a battery indicator and sound. My EFI is below:
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/12855908/EFI.zip)

**Comment by chris1111** [comment]
Delete EFI from Install SSD , Reboot to the USB on the ssd then retry the program then see the video about the installer Log 
send the Log if you have issue again.
