### ISSUE TITLE
Sierra loop create install USB

### ISSUE THREAD

**Issue by pydaniel** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#198]
hello chris, i have a problem to create a usb installer, this problema only with 10.12. I have a ssd to install and runing macOS, 10.13 or + works perfect, but 10.12 not! loop infinite using 100% of processor. How fix please?

**Comment by chris1111** [comment]
What do you mean by infinite loop using 100% CPU?

**Comment by pydaniel** [comment]
> What do you mean by infinite loop using 100% CPU?


here. only with 10.12, 10.13 and others works fine for me!

![Captura de Tela 2023-10-29 às 16 01 51](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/assets/145150616/b30cc58d-9afb-4691-968d-0fdd4df904ab)

**Comment by chris1111** [comment]
You said  `only with 10.12, 10.13 and others works fine` 
So what is the issue if it work fine on 10.12?

**Comment by pydaniel** [comment]
> You said `only with 10.12, 10.13 and others works fine` So what is the issue if it work fine on 10.12?

I meant that only version 10.12 doesn’t work, it gets stuck in a loop, endlessly recording the installer usb. From High Sierra onwards, it worked for me. The installation completes successfully

**Comment by chris1111** [comment]
Ok Sierra 10.12 is not on the[ Support List from Apple](https://support.apple.com/en-ca/HT201372), I think the support is removed?
