### ISSUE TITLE
How to even use this?

### ISSUE THREAD

**Issue by 0x6ff** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#199]
Hi!

I'm wanting to use Big Sur on a Probook 6570b which is currently running Windows 10 and Ubuntu 22.04.
From the looks of it, the installer seems to be for macOS only, but how are you supposed to run the installer to make an EFI and macOS USB if you're trying to get macOS running in the first place?
Are you supposed to run the installer on a different macOS install then use the USB on the hardware you're wanting to hackintosh?

**Comment by chris1111** [comment]
The guide is very clear, you must have a Mac to create the macOS BigSur11 USB key; With this USB key you install macOS on a blank SSD and not on a partition. this way you can boot mac and windows.

Even Linux after configurating OC for booting linux
