### ISSUE TITLE
boot after black image HP8570p

### ISSUE THREAD

**Issue by sajtos888** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#2]
Hello.  problem is that after boot when the apple logo should appear then i only get a black image.  However, I realized that the installation starts just throwing the image on the Display Port to an external display and the laptop display is black.
sorry for the google translator.

**Comment by chris1111** [comment]
Dont use external display for installing macOS

**Comment by sajtos888** [comment]
I don't want to use it but after loading the installer I only want to put the image on the external display even though no external display is plugged in.

**Comment by chris1111** [comment]
Give the complete description of the laptop, HP 8570p ?  the exact CPU and the laptop screen size, also do you have another Graphics device ?

**Comment by sajtos888** [comment]
Cpu: I5-3210M
Screen size: 1600x900
Intel HD 4000
no other graphics device

**Comment by chris1111** [comment]
For a High Screen resolution 1600x900  you need to ad **-igfxvesa** 

![Capture d’écran, le 2020-08-24 à 17 21 21](https://user-images.githubusercontent.com/6248794/91097765-4b093480-e62e-11ea-816b-01d83f8032fd.png)

**Comment by sajtos888** [comment]
I will try and indicate if it worked :)

**Comment by sajtos888** [comment]
hi sorry i am writing now just for lack of time i just tried it works perfectly :) thanks a lot!

**Comment by chris1111** [comment]
> hi sorry i am writing now just for lack of time i just tried it works perfectly :) thanks a lot!


Thanks to report 😇 I will add you to the tester Credit 🤝

**Comment by sajtos888** [comment]
Thank You! :smile:  Everything works perfectly. Except for Bluetooth I haven't been able to figure this out yet. Bluetooth worked with Catalina.
![Képernyőfotó 2020-08-27 - 17 34 08](https://user-images.githubusercontent.com/70166390/91463971-53f74180-e88c-11ea-8234-c048ee34c82d.png)

**Comment by chris1111** [comment]
What is the WIFI card you have?

**Comment by sajtos888** [comment]
Unfortunately the wifi card has not arrived yet.
Bluetooth is included. But to solve it I just had to add BrcmBluetoothInjector.kext in the OpenCore configurator.
It works.
![Képernyőfotó 2020-08-27 - 18 28 35](https://user-images.githubusercontent.com/70166390/91469038-2661c680-e893-11ea-847b-f90ef967b66b.png)

**Comment by chris1111** [comment]
Yes you have to Setup the bluthoot kext you have also to setup BrcmFirmwareData.kext 

See Video after Install program , I do this

**Comment by sajtos888** [comment]
Yes the video should have been watched :smiley: 
But the point is that it already works! :smile: 
Thanks! :smile:

**Comment by chris1111** [comment]
> Yes the video should have been watched 😃
> But the point is that it already works! 😄
> Thanks! 😄


What is the wifi card you have order?  ![296233927](https://user-images.githubusercontent.com/6248794/91471022-76c13000-e863-11ea-98f2-23d589c9f865.gif)

**Comment by sajtos888** [comment]
https://www.aliexpress.com/item/32879729616.html?spm=a2g0s.9042311.0.0.77cb4c4difKhrj 
I ordered this

**Comment by sajtos888** [comment]
Anyway, an Intel Centrino n-6205 wifi card is now included.
