### ISSUE TITLE
Mac OS version not yet set

### ISSUE THREAD

**Issue by onoakino** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#201]
Used the latest OC package creator as of writing this issue, and I am getting a kernel panic. Before the panic screen, I can read

Mac OS version:
Not yet set.

Device: HP elitebook 2570p
Package creator OC version: Latest Release Update 11 April 2023 (V-3)

**Comment by chris1111** [comment]
Which macOS would you try?
Which WiFi card do you use?

**Comment by onoakino** [comment]
I wanted to install Sonoma. So I used the latest OC package creator. I downloaded Sonoma 14.1.1. I used latest OC package creator to make a USB installer.

I was able to get to the install screen, but when it rebooted, i get the "os version not yet set."

I have BCM94352HMB wifi.

**Comment by chris1111** [comment]
You said when I reboot I have os version not set  yet 
Reboot after install macOS ?

**Comment by onoakino** [comment]
I did not reboot. In the middle of installation, the laptop rebooted itself. At first I thought to just let it be because I remember, even when installing Monterey, the installer would reboot itself for like 4 or 5 times, but then it would proceed and finish the installation successfully.

This time, the Sonoma installer would get the kernel panic after the first reboot from the GUI installer. The installation could not complete because of the kernel panic. It would automatically shutdown and reboot the laptop.

**Comment by chris1111** [comment]
Maybe your not reboot from the USB install drive

And yes it already testing see [here](https://www.hackintosh-montreal.com/t10381p450-hp-probook-elitebook-package-creator-oc#150207) Ivy Bridge is always testing by my official tester @djams

**Comment by onoakino** [comment]
I'm 100% sure it reboots from USB install drive. 

Do you have any other suggestions?

**Comment by chris1111** [comment]
If you are booting from USB install drive its impossible to have this king of KP
So issue is closed!
