### ISSUE TITLE
Aborting at installing macOS wait...

### ISSUE THREAD

**Issue by n0one42** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#206]
Hi there.
I am a pretty newbie with hackintosh so maybe it is my fault and I am missing something...

I have an HP Elitebook 850 G8 and I would like to install hackintosh on it.

Therefore I followed the Video "Create USB Ventura". At the step of Installing Media HP Laptop OC it starts, but it quits after some seconds.
It creates the Disk called "Install macOS Sonoma" (120 MB) but it is pretty empty and it also does not appear the "Install OpenCore USB" as in your video. What am I doing wrong?

I am also on a macos mini with Sonoma on it.

**Comment by chris1111** [comment]
HP Elitebook 850 G8 not support here see the guide.
