### ISSUE TITLE
No sound from speakers on Elitebook Folio 9470m

### ISSUE THREAD

**Issue by skajmer** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#207]
I installed Sonoma. There is no sound from speakers, only headphones work.

**Comment by chris1111** [comment]
Your Alc id should be 12 

alcid=12 check in config.plist 

You can try 11 ?

**Comment by skajmer** [comment]
It is 12. 11 is even worse, no outputs are displayed and headphones don't work aswell.

**Comment by chris1111** [comment]
Clear NVRAM at boot opencore, then restart

**Comment by skajmer** [comment]
No changes after doing that.

**Comment by chris1111** [comment]
Try `alcid=13`

**Comment by chris1111** [comment]
If its not working 

Setting up `alcid=13`  Add this `SSDT-HDEF.aml `in ACPI then enable the file in config.plist



[SSDT-HDEF.aml.zip](https://github.com/user-attachments/files/15998043/SSDT-HDEF.aml.zip)

**Comment by skajmer** [comment]
It works perfectly now. Thanks!

**Comment by chris1111** [comment]
> It works perfectly now. Thanks!


With [this ](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/207#issuecomment-2192801498)
