### ISSUE TITLE
package creator does not create dsdt on hp 9470m

### ISSUE THREAD

**Issue by robi62** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#208]
Hi Chris111 I have tried many times your package but it never create dsdt for my laptop 
Any ideas why is this happening I want to try to install Ventura or Sonoma but Im stuck with Monterey for the mo .Also when I tried on Catalina a few day ago it said all done but no refi created???
Very weird

**Comment by chris1111** [comment]
If the DSDT is not created, it is because you did not boot directly from the Install Media USB key created by the program and you must not modify the EFI folder of this USB key at any time.

**Comment by robi62** [comment]
I see I though that it would just create efi regardless Got it now Thanks

**Comment by chris1111** [comment]
everythings work now?

**Comment by robi62** [comment]
Nope twice same error 
![36F18D8F-0CF8-4314-BAF5-91F745218FBE](https://github.com/user-attachments/assets/7a1f1290-1a0f-41cb-8659-ab789866432b)
![BF445D3F-46C7-48DA-893E-45C1F69BD2F6](https://github.com/user-attachments/assets/94323f2d-3494-43fa-ad01-870adee14309)
![D7E19B34-D1CF-46BD-99AD-C3411EAFEDE9](https://github.com/user-attachments/assets/67f3d9ee-0e0e-44e0-ae0b-c729f064e210)

**Comment by robi62** [comment]
Strange enough the program wants to install efi not in Ventura install disk but on monterrey usb hard dik??

**Comment by robi62** [comment]
Can I actually run the program from a different laptop that is not hp9470m??

**Comment by robi62** [comment]
Ok Ill try that and get back to you

**Comment by robi62** [comment]
hi is the correct content of efi for installer Ventura??
I though the program would automatically choose which partition to install but I have to specify which portion is that correct???
![Screenshot 2024-07-30 at 11 36 55](https://github.com/user-attachments/assets/9965015a-2f94-49bf-83fa-2060c2454426)

**Comment by chris1111** [comment]
Not correct no DSDT

some thing wrong whit you because see here same laptop then all is correct except sound but I fix it.

https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/207

**Comment by robi62** [comment]
That s what your installer does both on hp 9470m and other hp
