### ISSUE TITLE
Slow SSD write speeds randomly on macos

### ISSUE THREAD

**Issue by ramyhq** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#211]
Hello Chris1111,

I have a ProBook 450 G1 with an i7-4910MQ, 16GB RAM, a 500GB SSD (CT5008X500SSD1), and macOS 14.1.1 (23B81).

I used this repo to create my EFI and made some adjustments to it.

Everything works great except for the SSD write speed, and I’m unsure what the issue might be.

Here’s the situation:

When browsing the internet, everything runs smoothly.
However, when working on Android Studio or Premiere Pro, the system randomly feels slow or starts hanging.
I ran a disk speed test and noticed the write speed is only 13–20 MB/s, while the read speed is nearly 500 MB/s.
Additionally:

This issue Also often occurs after the system has been asleep for an extended period (e.g., half a day or more).
I can sometimes resolve the problem with a couple of restarts, but it’s inconsistent.
Note: This issue does not occur in Windows 11, where the SSD performs very fast.

Could you suggest anything obvious I should check or update that might be affecting the write speeds?

Thank you for your help!

EFI: https://drive.google.com/file/d/109VWdCd22OUifs00OjWueJe7rQKvf9dJ/view?usp=sharing

![Screenshot 2024-11-21 at 3 16 40 PM](https://github.com/user-attachments/assets/555b62e7-2afa-457a-813c-76aad4200bb3)
![Screenshot 2024-11-21 at 3 16 35 PM (2)](https://github.com/user-attachments/assets/3310e0f6-d7ab-4b14-9b21-709641801f93)

**Comment by chris1111** [comment]
Verry difficult to solve because you have made a lot of modifications some are understandable because you have lintel HD 4600 on a 4X0 G1 which is not always the case. In addition you use an Intel Wifi card which can cause sleep and wake problems, so sorry I can not do anything for your problem.

**Comment by ramyhq** [comment]
Thank you for your reply and for taking the time to explain the challenges. I really appreciate your insights!

Could it be TRIM issue?
I wanted to ask about TRIM, as it seems to be disabled on my setup. I’ve tried enabling it using "sudo trimforce enable", but it disables itself after a couple of restarts. Could this be contributing to the write speed issue?

I’d appreciate any guidance or suggestions you might have regarding TRIM or other potential steps I can take.

Thanks again for your help!

Best regards,

**Comment by chris1111** [comment]
You could try  Kernel Patch / Trim for SSD  from OpenCore Configurator

![Screenshot 2024-11-21 at 8 19 38 PM](https://github.com/user-attachments/assets/07e5a982-0f73-4f2a-886c-420ed6ccb9e6)

**Comment by ramyhq** [comment]
Thank you so much, i patched it, and will wait to see if the problem solved.
But, do you think I should enable trim to solve this issue? 
or this is GPU related problem?

Im just looking for a hint to search for this issue

**Comment by chris1111** [comment]
after this patch Trim is support to enable in About this mac /System Repport/intel 8 Serie chipset/ trim support Yes

**Comment by ramyhq** [comment]
ok 
thank you for your time 
have a nice day

**Comment by chris1111** [comment]
I would be surprised if it was a simple trim problem.

**Comment by ramyhq** [comment]
i hope it is, for now every thing is normal and Trim is enabled.

I will start now coding and will see if this fix my problem.

Thanks again sooo much Chris

**Comment by chris1111** [comment]
[Update 22 Nov 2024](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/commit/7fa8958557dc40d52f76c6d61db91201fcb31fd9) Probook 4x0 G1 now has two choices
ProBook 4x0-G1 Intel HD 4400
ProBook 4x0-G1 Intel HD 4600
Not effected on release, only in build from Xcode

![Screenshot 2024-11-22 at 10 11 32 AM](https://github.com/user-attachments/assets/d80d0306-83ee-47d3-8bae-7678cbece9d4)

If you want, you can do a clean install again with the HP Create Install Media tool and do not change anything after the post installation

**Comment by ramyhq** [comment]
> i hope it is, for now every thing is normal and Trim is enabled.
> 
> I will start now coding and will see if this fix my problem.
> 
> Thanks again sooo much Chris

Unfortionatly, issue still exist after enable TRIM.

**Comment by ramyhq** [comment]
> [Update 22 Nov 2024](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/commit/7fa8958557dc40d52f76c6d61db91201fcb31fd9) Probook 4x0 G1 now has two choices ProBook 4x0-G1 Intel HD 4400 ProBook 4x0-G1 Intel HD 4600 Not effected on release, only in build from Xcode
> 
> ![Screenshot 2024-11-22 at 10 11 32 AM](https://private-user-images.githubusercontent.com/6248794/388988095-d80d0306-83ee-47d3-8bae-7678cbece9d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0ODE1NzksIm5iZiI6MTczMjQ4MTI3OSwicGF0aCI6Ii82MjQ4Nzk0LzM4ODk4ODA5NS1kODBkMDMwNi04M2VlLTQ3ZDMtOGJhZS03Njc4Y2JlY2U5ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjRUMjA0NzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBkZDU4ZDkzMjVmOTg0OWUwYWU0ZDgzNGI4ZjZiNWVjNmQwMmI1MGIwZjQ1ZGUzYmEzNDQyY2RhOWI1M2ZmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SwHxFCLHsTu23Dc6sFKmkrDgw6E_z29VWrYL1VisBYk)
> 
> If you want, you can do a clean install again with the HP Create Install Media tool and do not change anything after the post installation

Hello Again, 
Thank you soooooo much for your help.
I will try this new update and i hope this help solve the issue.

I'm so happy for your help ❤️
