### ISSUE TITLE
Problems with battery, sound, brightness... 9470m

### ISSUE THREAD

**Issue by apkspot** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#28]
Hello, I have HP Elitebook 9470m i5... I installed BigSur 11.1(20C69) and did the post installation correctly but nothing works, only graphics acceleration
The audio works only when I install VoodooHDA manually but couldn't manage to get everything else work. I was on Mojave and everything worked perfectly except for wifi because of the incompatibility.

this is my efi
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5703044/EFI.zip)

**Comment by chris1111** [comment]
Your EFI is not good 
Reinstall new macOS from USB installer erase the SSD
Probably your issue is from the High Screen laptop
See this https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/2#issuecomment-679373248
