### ISSUE TITLE
Can't get 3440x1440 resolution for external monitor. HP8570p (HD4000)

### ISSUE THREAD

**Issue by Cell5** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#3]
Hey Chris,
Did you try to connect hi-res external displays to your hackintosh?
In my case, everything works nearly great but the UltraWide monitor with 3440x1440 is able to operate on at 1080p only.
Whereas in Windows I can get it works, perhaps in Linux as well (not tested).
Will appreciate any advise.

Cheers,
Paul

**Comment by chris1111** [comment]
I not try, I only have 3 monitor 1080p
Seee on [WhateverGreen](https://github.com/acidanthera/WhateverGreen) maybe some boot args do this ?
