### ISSUE TITLE
Strange thing in Disk Utility

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#30]
Hi Chris,
After installing Big Sur in my HP ProBook 4440s (i3) everything works great thanks to your tutorial and files but I have noticed a couple of things:
![Captura de pantalla 2020-12-22 a las 6 10 12 p  m](https://user-images.githubusercontent.com/69108535/102915141-979c3980-4481-11eb-8c7b-db3c01a2af1d.png)
![Captura de pantalla 2020-12-22 a las 6 11 26 p  m](https://user-images.githubusercontent.com/69108535/102915151-9a972a00-4481-11eb-85e2-68f89b0518ec.png)
I don't know if the problems are related or not.
If there any way to fix that?
I had to use VBoxHFS.efi instead of HFSPlus.efi during and post install because HFSPlus caused panic kernel.
Do you need more information?
Thanks

**Comment by chris1111** [comment]
Ok but what is the problem here?

**Comment by antoniojveraa** [comment]
The strange thing is that I didn't know it. I was comparing it to Catalina. Sorry.

**Comment by chris1111** [comment]
> The strange thing is that I didn't know it. I was comparing it to Catalina. Sorry.

Not comparable to Catalina this is Big Sur support Apple Chip M1 and Intel CPU

![Capture d’écran, le 2020-12-22 à 13 44 01](https://user-images.githubusercontent.com/6248794/102922271-c8697800-445b-11eb-8018-24feec13f8be.png)

**Comment by chris1111** [comment]
Another question are you happy with your HP Probook with Sur? it works well for you

**Comment by antoniojveraa** [comment]
Oh yes, very happy. The laptop is old but everything works fine. I'm using your DSDT and Open Core was kind of scary for me since I used Clover for a long time. Some things make the think like why VBoxHFS.efi instead of HFSPlus.efi and the AppleAPFS is still there.
Thanks once again.

**Comment by chris1111** [comment]
> Oh yes, very happy. The laptop is old but everything works fine. I'm using your DSDT and Open Core was kind of scary for me since I used Clover for a long time. Some things make the think like why VBoxHFS.efi instead of HFSPlus.efi and the AppleAPFS is still there.
> Thanks once again.

Somes HP model works with Vbox and the AppleAPFS.efi is need because without it the partition is not visible
OpenCore is not perfect is on development everyday

**Comment by antoniojveraa** [comment]
I tried to install Big Sur with Clover 5127 but it is bigger than me and I couldn't make my PC boot so I stayed at 5123.
Would be any difference in performance using Clover or OC?

**Comment by chris1111** [comment]
About Vbox take a look here, its now part of OC Build
https://github.com/acidanthera/OpenCorePkg/commit/128f20cbd59b29a6933e70d23dfed2f9e247032d

**Comment by antoniojveraa** [comment]
Chriss, I used to use Clover occording to your tutorial when I had Catalina installed. Now that I upgraded to Big Sur and change to Open Core, I have a new devide in Windows:
![Captura](https://user-images.githubusercontent.com/69108535/103148682-affea380-4762-11eb-978e-aa9d11bb1010.PNG)
Do you know why and how to solve this?
