### ISSUE TITLE
Black screen when I boot installer USB

### ISSUE THREAD

**Issue by yuyu898** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#31]
hi chris1111,
First of all thank you for providing such useful HP hackintosh tutorial. I just followed your tutorial to make installer USB and tried to boot the USB and all I got is black screen. I already added -igfxvesa but still the same.

Hardware Spec:
1. HP Probook 4540s i3-3110M version
2. 1920 x 1080 screen resolution
3. 16GB of RAM
4. System BIOS Version: F.68 ( Could this cause the probem?)

Please advise and thak you so much.
I attached some files you might need to take a look:
Here is video clip link: https://drive.google.com/drive/folders/0BzRq0mt6OgZ0YlZ1dUstWlhHckU?usp=sharing
![Screen Shot 2020-12-25 at 2 38 22 PM](https://user-images.githubusercontent.com/76600806/103142847-fe0e9b00-46bf-11eb-9745-8314ac25f32d.png)

**Comment by chris1111** [comment]
Use VboxHFS not HFSPlus

**Comment by yuyu898** [comment]
Hi chris1111,
Thanks for your quick reply. I just replaced HFSPlus with VboxHFS and nothing changed unfortunately. Let me upload my efi folder which might be easier for you to troubleshoot the issue. Thank you for your time and wishing you have a wonderful holiday.

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5742595/EFI.zip)

**Comment by chris1111** [comment]
I don't know what doesn't work for you because all those who have a 1600x900 screen needed -igfxvesa for it to work and for you it doesn't work it's weird ?

**Comment by yuyu898** [comment]
yes, it's so weired. Thank you for your time and guess I just keep using Catalina for now.
