### ISSUE TITLE
layout id for 4340s

### ISSUE THREAD

**Issue by shajek** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#32]
hello, i only want to say, that probook 4340s has layout id 13 , not 12

**Comment by chris1111** [comment]
Ok thanks did you install Big Sur with the program?

**Comment by shajek** [comment]
yes, thank you too. I have to change alcid to 13, when I delete it, and change layoutid in device properties it is not working. Only as boot arg.
Another thing is, that 8111 kext is included, but not in config plist, I have to add it too, and remove mausi

but I have one problem, console is distorted, I try force resolution but nothing, OC GUI is nice, apple logo is nice, but when -v is distorted. Do you have any advice to fix it ?

btw. I update oc to 0.6.4 and it works :)

**Comment by joseparedespy** [comment]
Thank you very much for this great guide @chris1111 
As a comment, I have the Hp ProBook 4540s and I also use the layoud id 13
![Captura de Pantalla 2020-12-28 a la(s) 13 42 15](https://user-images.githubusercontent.com/19367073/103229913-d5caaa80-4912-11eb-8c65-7bc3fa364e42.png)

**Comment by shajek** [comment]
Work for you layoutid, or you must use bootarg alcid?
Thank you

**Comment by joseparedespy** [comment]
The boot-args I have it working like this.
![Captura de Pantalla 2020-12-28 a la(s) 14 01 04](https://user-images.githubusercontent.com/19367073/103230920-55f20f80-4915-11eb-84bb-9fd1ef9b168b.png)
