### ISSUE TITLE
Can Zbook support be added

### ISSUE THREAD

**Issue by Thatisjigen** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#33]
Not an issue tbh, but can be added the support for the zbook G1? (Haswell, have Rehabman patches as the elitebook and probook)

**Comment by chris1111** [comment]
I known but not for now, maybe I add support in the future

**Comment by chris1111** [comment]
what is the HP Zbook you have exactly

**Comment by Thatisjigen** [comment]
ZBook G1 15, i got a working OC setup for big sur, you can mail me if you need=>jigen.aka.jayel@gmail.com

**Comment by chris1111** [comment]
Simply post EFI on ZIP here I will see
