### ISSUE TITLE
HP Elitbook 8470p i7 with AMD Radeon HD 7650M

### ISSUE THREAD

**Issue by zendzo** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#34]
Hi,
i successfully install macos bigsur with this package creator.
unfortunately i unable to switch to intel HD since there is no option in bios.
and amd radeon only show 3mb which is make display too low.
how do i patch this issue?

**Comment by chris1111** [comment]
See WatherveGreen boot args to disable Completely ATI/AMD 
https://github.com/acidanthera/WhateverGreen

**Comment by zendzo** [comment]
hi @chris1111 

i tried to disable eGPU, by boot-args
after restart Graphics show *Display 3 MB*, it seems i this laptop unable to disable eGPU
how to increase value of AMD Radeon 3 MB?

but i read some post [AMD Radeon 7650M Working](https://www.hackintosh-forum.de/forum/thread/35456-hp-8470p-fixes/?postID=383142#post383142)

**Comment by chris1111** [comment]
> hi @chris1111
> 
> i tried to disable eGPU, by boot-args
> after restart Graphics show _Display 3 MB_, it seems i this laptop unable to disable eGPU
> how to increase value of AMD Radeon 3 MB?
> 
> but i read some post [AMD Radeon 7650M Working](https://www.hackintosh-forum.de/forum/thread/35456-hp-8470p-fixes/?postID=383142#post383142)

send me EFI folder on ZIP

**Comment by zendzo** [comment]
Hi @chris1111 

EFI Folder attached.

[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5756269/EFI.zip)

**Comment by chris1111** [comment]
Follow this video from Mald0n for disable AMD gpu
https://www.youtube.com/watch?v=Vzb8X-BL3Cg
