### ISSUE TITLE
Boot menu only shows reset NVRAM (HP Probook 450 G1)

### ISSUE THREAD

**Issue by abmomin** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#37]
**I don't know where to ask for help that's why I am raising this issue.**
My Laptop Config:
Brand: HP Probook 450 G1
Processor:  Intel(R) Core(TM) i5 4200M CPU @ 2.5GHz
Ethernet: Realtek PCIe GBE Family Controller
Wifi Adapter: Mediatek MT760E 802.11bgn Wifi Adapter 
Bluetooth: Mediatek Bluetooth Adapter
Graphics: Intel(R) HD Graphics 4600
Motherboard:  Intel motherboard 734085-501 hm87 ddr3 (i think so)

**What I did:**
Downloaded the repository (HP-Probook-EliteBook-Package-Creator-OC) downloaded the Mac OS Big Sur and Catalina from AppStore. First, I tried with Big Sur.
* Ran Gatekeeper.command to disable Gatekeeper
* Ran Packager.command which created 
* Selected options A and B, one after another 
* Then created bootable USB using  Install Media HP Laptop OC.app
this process finished with a warning saying could not copy some icon (don't actually remember).
and pressed ok and this app was closed automatically and did not open any other app like saw in video instruction.
So I ran the HP-Probook-Elitebook-macOS.pkg and selected the pen drive on which I created the bootable USB.and finished the process. After this, I tried to boot from USB on my laptop.

**My BIOS have:**
* Fast boot disabled
* SATA AHCI(I have only this option available)
* My USB is USB 3.0 and I am trying to boot using my laptops USB 3 port (USB 2 port broken)

**Problem:**
After booting from USB it only shows the reset NVRAM option and if I press enter it turns off and comes back with the same option. Before this option shows up on the screen this message quickly appears and disappears. it says (OC:  Failed to find ACPI DSDT.aml)

**Sorry if I am doing any mistake could not find anything on google about this issue.**

**Comment by chris1111** [comment]
Are you sure you follow video ? Did you see in Video
Were you see that on the video ➡︎ **ran the HP-Probook-Elitebook-macOS.pkg and selected the pen drive**
