### ISSUE TITLE
Problem with Windows after Opencore install

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#39]
My PC is an HP Probook 4440s (i3) and I installed Big Sur following your instructions.
Before upgrading to BS, I was using Catlina also installed following your tutorial with Clover. Unfortunatly, I had to move to Opencore because I could not configure Clover to boot Big Sur.
When I boot into Windows using Opencore I get this:
![With Opencore](https://user-images.githubusercontent.com/69108535/105022665-4f554480-5a4a-11eb-9678-b09d6618bdc3.jpg)
And when I boot using Clover (not working for BigSur) I get this:
![With Clover](https://user-images.githubusercontent.com/69108535/105022754-66943200-5a4a-11eb-8dcf-7a47761a9df9.jpg)
When I boot using OC I get one unrecognized device: ACPI\FAN00000\2&DABA3FF&0
And HP Support Software does not recognize my PC as HP.
Is this normal? Any way to fix it since I couldn't configure Clover

**Comment by chris1111** [comment]
see SMBIOS SpoofVendor ?

**Comment by antoniojveraa** [comment]
Sorry but I didn't get it.

**Comment by chris1111** [comment]
![Capture d’écran, le 2021-01-19 à 09 34 13](https://user-images.githubusercontent.com/6248794/105048453-9981fa00-5a39-11eb-81e1-12a5d1b18d0c.png)

**Comment by antoniojveraa** [comment]
It was checked so I uncheck it.
HP Software still does no recognize model ans still the unrecognized hardware is there.
![Imagen 01](https://user-images.githubusercontent.com/69108535/105061330-b2120480-5a79-11eb-9eee-97970bfcfb23.jpg)
![Imagen 02](https://user-images.githubusercontent.com/69108535/105061332-b2aa9b00-5a79-11eb-8c2f-e850d1766622.jpg)
![Imagen 03](https://user-images.githubusercontent.com/69108535/105061336-b2aa9b00-5a79-11eb-8f68-44062899fb3a.jpg)
![Imagen 04](https://user-images.githubusercontent.com/69108535/105061337-b3433180-5a79-11eb-8fd8-eab83cf7f9b1.jpg)
![Imagen 05](https://user-images.githubusercontent.com/69108535/105061339-b3433180-5a79-11eb-851c-bc6fd2ee2725.jpg)
