### ISSUE TITLE
Card reader can't work for macOS Catalina

### ISSUE THREAD

**Issue by salut0714** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#41]
Hello Chris ,

Today I just downloaded your package to install Catalina on my HP-8470P.
Everything is working , only the card reader can't work.
I am sure the card reader is OK on windows 10.
Also the SD card host controller can be found on PCIe with Hackintool
Please help me to solve this problem.

Thank you.

**Comment by chris1111** [comment]
Did you follow this [Card Reader Fix](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC#card-reader-fix-for-macos-big-sur-11-only)
If the card reader is a JMicron its work with this

**Comment by salut0714** [comment]
I didn't follow this "Card Reader Fix"
It's useful for Catalina. right ?
Yes ,the card reader is a JMicron

**Comment by chris1111** [comment]
> I didn't follow this "Card Reader Fix"
> It's useful for Catalina. right ?
> Yes ,the card reader is a JMicron


This fix is for Big Sur 
Catalina the kext is simply Inject by OpenCore

**Comment by salut0714** [comment]
Do you mean I just put JMB38X.kext and HSSDBlockstorage.kext to the "kexts of OC ", and enable them in config.plist,right ?

**Comment by chris1111** [comment]
yes

**Comment by salut0714** [comment]
strange ! still can't work.

**Comment by chris1111** [comment]
> strange ! still can't work.



So remove from OC then use this https://github.com/chris1111/Kext-Droplet

**Comment by salut0714** [comment]
Thank you very much ! It's working
