### ISSUE TITLE
Big Sur Installer reboot to bootloader

### ISSUE THREAD

**Issue by ostadnart** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#42]
I created a big Sur USB installer by your video guide.(probook...pakage)
Without adding any file to efi folder.
For fresh install I formated my Mojave partition.
When I start to install big Sur,installer reboot to bootloader
In verbos this is the last line:
smcsuperio. ssio: @ failed to detect supported superio chip

I created installer exactly like as your video guide.

**Comment by chris1111** [comment]
Laptop?  Hardware? Image? nothing

**Comment by ostadnart** [comment]
Excuse me.
Laptop,probook 4540s.

**Comment by chris1111** [comment]
> Excuse me.
> Laptop,probook 4540s.

Seriously this is not infos about the laptop

**Comment by ostadnart** [comment]
I try to install Yosemite by old installer USB(clover) to access big Sur USB
Then send you efi folder

**Comment by ostadnart** [comment]
i installed mac yosemite  and tried to use probe ...pajage to create big sur usb installer but when select big sur installer app this error show :
dyld: Library not loaded: @executable_path/../Frameworks/IAESD.framework/Versions/A/IAESD
  Referenced from: /Applications/Install macOS Big Sur.app/Contents/Resources/createinstallmedia
  Reason: no suitable image found.  Did find:
	/Applications/Install macOS Big Sur.app/Contents/Resources/../Frameworks/IAESD.framework/Versions/A/IAESD: mmap() error 1 at address=0x104864000, size=0x00008000 segment=__TEXT in Segment::map() mapping /Applications/Install macOS Big Sur.app/Contents/Resources/../Frameworks/IAESD.framework/Versions/A/IAESD
	/Applications/Install macOS Big Sur.app/Contents/Resources/../Frameworks/IAESD.framework/Versions/A/IAESD: mmap() error 1 at address=0x10487C000, size=0x00008000 segment=__TEXT in Segment::map() mapping /Applications/Install macOS Big Sur.app/Contents/Resources/../Frameworks/IAESD.framework/Versions/A/IAESD
