### ISSUE TITLE
Config Checker

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#43]
Chris,

I just installed Big Sur on my i3 ProBook 4440s using your apps. Everything goes fine but I have a question:
When I check config.plist using Opencore Configurator I can see some yellows and reds.
Did you configure the config.plist on purpose for this machine or shall I change the yellows and reds to meet Config Checker specs?
Will changing this affect the performance or connectivity or something else?
Why ig-plataform-id is not set? Not needed it?
What about GlobalConnect on APFS?
![Captura de pantalla 2021-02-19 a las 9 14 49](https://user-images.githubusercontent.com/69108535/108538510-bb1e0d80-7293-11eb-9f46-1b9c515c0a24.png)
![Captura de pantalla 2021-02-19 a las 9 15 15](https://user-images.githubusercontent.com/69108535/108538515-bc4f3a80-7293-11eb-9407-9fab584880ed.png)
![Captura de pantalla 2021-02-19 a las 9 14 57](https://user-images.githubusercontent.com/69108535/108538517-bce7d100-7293-11eb-9f87-6d03b5f51e9e.png)
![Captura de pantalla 2021-02-19 a las 9 14 10](https://user-images.githubusercontent.com/69108535/108538519-bce7d100-7293-11eb-8870-da99eeca1d2c.png)
![Captura de pantalla 2021-02-19 a las 9 14 18](https://user-images.githubusercontent.com/69108535/108538524-be18fe00-7293-11eb-8b8f-5e6b7eeba59f.png)
![Captura de pantalla 2021-02-19 a las 9 15 07](https://user-images.githubusercontent.com/69108535/108538526-be18fe00-7293-11eb-9d4e-7ddd385816c0.png)
![Captura de pantalla 2021-02-19 a las 9 14 27](https://user-images.githubusercontent.com/69108535/108538527-beb19480-7293-11eb-9186-0370abc91d81.png)
![Captura de pantalla 2021-02-19 a las 9 14 37](https://user-images.githubusercontent.com/69108535/108538531-bf4a2b00-7293-11eb-996a-7564b64e4bd5.png)

**Comment by antoniojveraa** [comment]
![Captura de pantalla 2021-02-19 a las 9 13 58](https://user-images.githubusercontent.com/69108535/108544894-63a98d00-72e7-11eb-9e48-525d8490cbd7.png)
![Captura de pantalla 2021-02-19 a las 9 13 40](https://user-images.githubusercontent.com/69108535/108544897-64422380-72e7-11eb-8e4f-098e686e8a42.png)

**Comment by chris1111** [comment]
Use the good verificator this app use the Achidentera ocvalidate
https://github.com/chris1111/Config-Validator
