### ISSUE TITLE
4540s F.68 Unable to boot from USB

### ISSUE THREAD

**Issue by m4t7e0** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#44]
My BIOS Setup is as requested:

Default setup
Disable LAN/WLAN Switching
UEFI Hybrid with CSM
Disable FastBoot

My USB was create by other Hackinthos (booted by clover) and Gatekeper disabled.
Package are download yesterday.

I Followed these step:
"Compiled"  as "https://www.youtube.com/watch?v=0M10TUtsnGA"
- Initialized 16GB USB3 Drive 
- Selected "to BigSur"
- Customized OpenCore "https://user-images.githubusercontent.com/6248794/90392185-67b8d180-e05c-11ea-983b-dc5f463e4f2e.gif"

TEST 1
- REMOVED ALL any file *.aml in /EFI/OC/ACPI/ [SSDT-HMF and SSDT-IGPU]

4540S Boot with ONLY THIS USB and one hard drive,

F9  -> Boot From EFI File -> Selected EFI USB DRIVE -> Selected EFI -> Selected OC -> OpenCore.efi  ----> "BLACK Screen"

TEST2 
- WITHOUT REMOVE [SSDT-HMF and SSDT-IGPU]
4540S Boot with ONLY THIS USB and one hard drive,

F9  -> Boot From EFI File -> Selected EFI USB DRIVE -> Selected EFI -> Selected OC -> OpenCore.efi  ----> "BLACK Screen"

TEST3
- WITHOUT REMOVE [SSDT-HMF and SSDT-IGPU]
- ADDED -igfxvesa in config.plist 
4540S Boot with ONLY THIS USB and one hard drive,

F9  -> Boot From EFI File -> Selected EFI USB DRIVE -> Selected EFI -> Selected OC -> OpenCore.efi  ----> "BLACK Screen"

What's is going on?

**Comment by chris1111** [comment]
Why remove file6 No body tell us to remove file Simply not adding AML file
