### ISSUE TITLE
Dim Light and Reduced Graphic Quality

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#47]
Hi, I have just installed Big Sur on Hp Elitebook 8470p (corei5 3rd gen, Intel HD 4000) by following your guide... Everything is working very well... You are a Hero of Hackintosh bro... Thank Thanks a lot.
The only issue I am facing is Brightness is dim, 70% of original brightness also the graphic quality is low. It looks like the CPU is getting low Power. Moreover, In system Information, my processor is represented as 2.6 GHz core i7 processor but it is actually Core i5. I am using the default SMBIOS it is MacBookPro15,4.

My open-core folder without wifi kexts:
[OC.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6049478/OC.zip)

**Comment by chris1111** [comment]
Send me complete report System (About this Mac)  ZIP file

**Comment by afzl-wtu** [comment]
System Report: 
[System report Big Sur and WIndows10.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6050820/System.report.Big.Sur.and.WIndows10.zip)

**Comment by afzl-wtu** [comment]
> 
> 
> Send me complete report System (About this Mac) ZIP file

I have attached system reports of both Big Sur and Windows 10. Please check

**Comment by chris1111** [comment]
You can try some MacBook Air compatible BS 
Let me known if that works

**Comment by afzl-wtu** [comment]
> 
> 
> You can try some MacBook Air compatible BS
> Let me known if that works

If I change my SMBIOS data, I have to remap my USBs and other stuff? or please just point me to some guide.

**Comment by chris1111** [comment]
> > You can try some MacBook Air compatible BS
> > Let me known if that works
> 
> If I change my SMBIOS data, I have to remap my USBs and other stuff? or please just point me to some guide.


No everything is patch by DSDT
Simple try another System definition MacBook Air compatible BS

**Comment by afzl-wtu** [comment]
> 
> 
> > > You can try some MacBook Air compatible BS
> > > Let me known if that works
> > 
> > 
> > If I change my SMBIOS data, I have to remap my USBs and other stuff? or please just point me to some guide.
> 
> No everything is patch by DSDT
> Simple try another System definition MacBook Air compatible BS

Ok I will try now. and tell you soon

**Comment by afzl-wtu** [comment]
Did you find any error in system information?

**Comment by chris1111** [comment]
Only about CPU

**Comment by chris1111** [comment]
And please Upgrade to a nice SSD you will see now how macOS is cool and fast

**Comment by afzl-wtu** [comment]
Can I try MacBookPro11,1?

**Comment by chris1111** [comment]
no

**Comment by afzl-wtu** [comment]
> 
> 
> And please Upgrade to a nice SSD you will see now how macOS is cool and fast

My HDD is quite fast amazingly. But Thanks for the suggestion.

**Comment by chris1111** [comment]
This is not comparable of HP Pro SSD

**Comment by afzl-wtu** [comment]
So how I know which SMBIOS will be suitable, Every time I need to gen serial number through GenSMBIOS?

**Comment by afzl-wtu** [comment]
I saw in your random commit you said you were using MacBookPro11,1

**Comment by chris1111** [comment]
BS first release this is not working anymore

**Comment by afzl-wtu** [comment]
MacBookAir6,2

https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#macbook-air...

I try this.

**Comment by chris1111** [comment]
Try MacBookAir9,1

**Comment by afzl-wtu** [comment]
hahahah,,, Guides say stay close as possible but bro you say try the latest one.... Ok sir I follow you...

**Comment by chris1111** [comment]
> hahahah,,, Guides say stay close as possible but bro you say try the latest one.... Ok sir I follow you...


Don't think that the other guides have the absolute truth here we some of old guru

**Comment by afzl-wtu** [comment]
hahhahahh Guru.... Guru is Hindi (Indian) language word and it means Teacher of Teachers.... What it will take if I want to be your student Guru G? I am from India.

**Comment by chris1111** [comment]
Iam A 
![2409935866](https://user-images.githubusercontent.com/6248794/109329632-d4d9ca80-7828-11eb-8474-89ed21f5d0a0.png)
Canadian  GURU 
![1037447622](https://user-images.githubusercontent.com/6248794/109329666-ddca9c00-7828-11eb-9141-910e2cec9c6f.gif)
![637945067](https://user-images.githubusercontent.com/6248794/109329693-e4f1aa00-7828-11eb-800a-62b5e63be800.gif)

**Comment by afzl-wtu** [comment]
oh I see, It i snow going to be unprofessional, but It is very nice to meet you.

**Comment by afzl-wtu** [comment]
MacBookAir9,1 have only 12watt cpu

**Comment by chris1111** [comment]
> oh I see, It i snow going to be unprofessional, but It is very nice to meet you.

Thanks I've never classed myself as a pro in anything I do

**Comment by afzl-wtu** [comment]
Oh sorry sorry bro, I though we can not comment on a closed issue.. I am really sorry.

**Comment by afzl-wtu** [comment]
I dont know much about github. sorry

**Comment by afzl-wtu** [comment]
> > oh I see, It i snow going to be unprofessional, but It is very nice to meet you.
> 
> Thanks I've never classed myself as a pro in anything I do

Hey bro, I just fixed the dim light issue. I reinstalled the Big Sur with MacBookPro16,4. and before installation I maxed my laptop brightness on Windows 10 and also after running post installation software, I configured new config.plist and added MacBookPro16,4 SMBios there too and then I rebooted.
