### ISSUE TITLE
Dim Light and Wrong CPU Model

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#48]
Hey, bro please don't close the issue until it is resolved, because it is a real issue.

I have tried 3 SMBioses MacBookAir9,1 and MacBookPro11,4 but they do not have any effect on the brightness or CPU model.
Maybe there is some problem with kexts or ACPI patches.

If you can guide me in debugging, I have basic knowledge of config.plist but never played with SSDT and DSDT. I can help you in testing on Hp Elitebook 8470p.

**Comment by afzl-wtu** [comment]
In config.plist>PlatformInfo 
why we have three sections (DataHub,Generic and SMBIOS) instead of Single Generic item? It becomes difficult when we change the SMBIOS

**Comment by chris1111** [comment]
You have already open issue here this one will delete 
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/47
