### ISSUE TITLE
OC Package creator for 6570b

### ISSUE THREAD

**Issue by DomiDomian** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#49]
Hi Chris, i tried your Package Creator, also the Clover Version but nothing works. I bootet with no acpis ran your installer but nothing works. what is wrong with it?

**Comment by chris1111** [comment]
I have this laptop and also many user so follow the guide correctly

**Comment by DomiDomian** [comment]
the thing is i only get dsdt.dsl but not dsdt.aml i followed exactly your videos but without success :(

**Comment by chris1111** [comment]
Impossible if you follow correctly Read the guide again :(

**Comment by DomiDomian** [comment]
ok i tried multiple times, download the newest version of your package and now it worked. Thank you very much!

**Comment by chris1111** [comment]
It is the same, only the Readme file as change :(
