### ISSUE TITLE
How to enable other wifi?

### ISSUE THREAD

**Issue by Bogey** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#5]
Hi Chris,

I have a 8470p running osx stable with Rehabman’s hotpatch guide since he first published it. Can I use these ssdt files?

I followed your guide to the letter and was able to run Catalina on my 8470p with i5. 
However, I could not get wifi to work. It’s a DW1560 ( Bcm94352z ).

Can you assist please? 

Thanks,
B.

**Comment by chris1111** [comment]
attach EFI please

**Comment by Bogey** [comment]
[OpenCore EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5285335/OpenCore.EFI.zip)
[Clover EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5285345/Clover.EFI.zip)
Please find attached the created OC EFI and my working Clover EFI.

**Comment by Bogey** [comment]
After booting with Clover, hackintool reports the wifi in the pci tab as 4352. Booting with opencore reports it as 4360.

**Comment by chris1111** [comment]
Try this DSDT with EFI OpenCore If its not work simply use a diferant SMBIOS **MacBook Pro 15.1** generate new serial number and ROM
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5288429/DSDT.aml.zip)

**Comment by Bogey** [comment]
Thanks!
Unfortunately, it made no difference: still no wifi. 
I tried SMBIOS 9,2 10,2 11,1 and 15,1 - I tested with the old and the new DSDT and no DSDT. 

I've never had any problems with this card, so I'm really pulling my hair why it's not discovered.

**Comment by Bogey** [comment]
![IMG_0483](https://user-images.githubusercontent.com/866768/94421098-5a2b5700-0185-11eb-88de-0f253ac08928.JPG)
This is the card. It says +BT, but that doesn't work on Clover either. 
So I installed the HP module (see other picture). That one works via BIOS, but for whatever reason does not work with BrcmPatchRAM. So I disabled it.

I have bluetooth now enabled with a 'GMYLE Bluetooth 4.0 Dual Mode Micro USB Broadcom BCM20702 Adapter Dongle'.
(so there are 3 bluetooth adapters installed and only one works)

**Comment by chris1111** [comment]
I have also the same card and no issue here on Catalina and Big Sur

Try se this kext for Catalina
[Archive.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5291954/Archive.zip)

**Comment by Bogey** [comment]
Only after I added these kexts to config.plist wifi works.
It seems the package creator did not create entries for wifi and Bluetooth.
While I was at it, I also installed SidecarEnabler.kext. Everything seems to work well 😁

**Comment by chris1111** [comment]
> Only after I added these kexts to config.plist wifi works.
> It seems the package creator did not create entries for wifi and Bluetooth.
> While I was at it, I also installed SidecarEnabler.kext. Everything seems to work well 😁


this is normal because i have put the enfase on big on 11 and surely the wifi kexts only work for big on 11 i will advise users to use other kext if they use catalina.
Thank you for bringing it back

**Comment by Bogey** [comment]
Thanks for creating such a wonderful tool!

**Comment by Bogey** [comment]
One more question, boot log shows:
`Dependency com.apple.iokit.IOHIDSystem fallback to com.apple.iokit.IOHIDFamily succeeded. Please fix your kext!`
How can I fix that?

**Comment by chris1111** [comment]
> Thanks for creating such a wonderful tool!

Thanks

**Comment by chris1111** [comment]
[Tester Bogey is now on the Credit](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/commit/e6eb41e137c220f3f08b4a8776a8f2516a59e133) 😀

**Comment by ieseberri** [comment]
> Only after I added these kexts to config.plist wifi works.
> It seems the package creator did not create entries for wifi and Bluetooth.
> While I was at it, I also installed SidecarEnabler.kext. Everything seems to work well 😁

Hello Bogey,

I've got the same issue but I'm still learning and I don't know how I can add those files to config.plist. Please, can you give a step by step guide to do it? Thank you!

**Comment by Bogey** [comment]
Here’s shown at 15:42 how to add kexts to opencore config.plist
https://youtu.be/n69xHovy0XE?t=942

**Comment by ieseberri** [comment]
Hello Bogey,

I've run hackintool and I'm not able to see the wifi card, there is no Broadcom register. I've run a Linux Live distro and WIFI card seems to be ok, it works in Linux. Do you know what can I do? Could be something connected with BIOS settings, or can be related with Catalina release? Thank you.

**Comment by Bogey** [comment]
I don’t know what wifi card you have. It might be one that’s not supported?

**Comment by ieseberri** [comment]
I've got Azurewave AW-CE123H BCM94352HMB...

**Comment by Bogey** [comment]
I used this https://github.com/acidanthera/AirportBrcmFixup
