### ISSUE TITLE
Turbo Boost not working

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#50]
Hey bro, Turbo boost is not working on HP EliteBook 8470p. I have enabled VT-x in Bios and using Intel Power Gadget.
[MacBook Pro.spx.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6068761/MacBook.Pro.spx.zip)

**Comment by chris1111** [comment]
Turbo boost works with [SSDT Prgen](https://github.com/Piker-Alpha/ssdtPRGen.sh)

**Comment by afzl-wtu** [comment]
> Turbo boost works with [SSDT Prgen](https://github.com/Piker-Alpha/ssdtPRGen.sh)

Can I Use this aml with your acpi folder or I have to regenerate all?

**Comment by afzl-wtu** [comment]
> Turbo boost works with [SSDT Prgen](https://github.com/Piker-Alpha/ssdtPRGen.sh)

When I run the SSD Prgen:

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2021 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <
/Users/afzl_wtu/Downloads/Compressed/ssdtPRGen.sh-Beta/ssdtPRGen.sh: line 3877: /Users/afzl_wtu/Library/ssdtPRGen/Data/Versions.cfg: No such file or directory

System information: macOS 11.2.1 (20D75)
Brandstring: "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz"

Notice: Downloading extractACPITables.zip ...
Notice: Downloading User Defined.cfg ...
Notice: Downloading Sandy Bridge.cfg ...
Notice: Downloading Ivy Bridge.cfg ...
Version: models.cfg v171 / Ivy Bridge.cfg v150


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Notice: Downloading Restrictions.cfg ...
Generating ssdt.dsl for a 'MacBookPro16,2' with board-id [Mac-5F9802EFE386AA28]
Ivy Bridge Core i5-3230M processor [0x306A9] setup [0x0701]
With a maximum TDP of 35 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 2600 MHz)
Number of Turbo States: 6 (2700-3200 MHz)
Number of P-States: 21 (1200-3200 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: Model identifier (MacBookPro16,2) not found in..: /S*/L*/CoreServices/PlatformSupport.plist


Error: board-id [Mac-5F9802EFE386AA28] not supported by Ivy Bridge – check SMBIOS data / use the -target option

Do you want to continue (y/n)?
