### ISSUE TITLE
Magenta Colors Fix

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#51]
Hey bro sorry to bother you again, I have found the real cause behind the screen brightness and low graphic quality on my HP Elitebook 8470p Big Sur. Colors on my laptop screen or not accurate blue color is like indigo and grey color has changed to pink color. Same exact to the issue in this video: [FIX Mojave Catalina MAGENTA MONITOR](https://youtu.be/JlcqAwoNz-Y)
This fix in video suggest to modify System>Display.  Please help.

**Comment by chris1111** [comment]
you have already issue for display fix , and you can fix yourself
