### ISSUE TITLE
No Sound on internal Speakers (9470m)

### ISSUE THREAD

**Issue by 9470m** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#52]
I installed Big Sur 11.2 on my HP Elitebook 9470m.
So far everything works fine but there is no sound from the internal speakers, although the system detected the internal speakers and the internal microphone is working well.
Can you please help me what do try?
Thank you!
![Bildschirmfoto 2021-03-08 um 00 11 50](https://user-images.githubusercontent.com/80227182/110258448-f82c1480-7fa2-11eb-819c-113726207eaf.png)
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6098131/EFI.zip)

**Comment by chris1111** [comment]
Try different boot args default is alcid=12  
Try alcid=11

**Comment by 9470m** [comment]
With alcid=11 the output devices unfortunately aren't there anymore
![Bildschirmfoto 2021-03-08 um 00 29 36](https://user-images.githubusercontent.com/80227182/110258959-78537980-7fa5-11eb-94e5-b4093d2e819f.png)

**Comment by chris1111** [comment]
Make sur with 11 you have selected the right  thing here

![Capture d’écran, le 2021-03-07 à 18 36 47](https://user-images.githubusercontent.com/6248794/110259155-4970df80-7f74-11eb-9f57-bc33b9888f69.png)

**Comment by 9470m** [comment]
I Tried this, but unfortunately this also did not help.
The internal Speakers still don't work. (No Hardware Issue; I tried my old SSD with OS X 10.14 to check).
But with ALC ID 12 the Sound with the Headphones in the 3,5mm Line Output does work on Big Sur.

**Comment by chris1111** [comment]
Try this
https://github.com/chris1111/VoodooHDA-OC

**Comment by 9470m** [comment]
I did some "Trial and Error" stuff around the AlcID. alcid=13 did solve my problem. :)
Thanks a lot for your support. I appreciate your work very much!

**Comment by chris1111** [comment]
> I did some "Trial and Error" stuff around the AlcID. alcid=13 did solve my problem. :)
> Thanks a lot for your support. I appreciate your work very much!

Thanks
