### ISSUE TITLE
Problems with Probook 6570b

### ISSUE THREAD

**Issue by Berstanio** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#55]
I have a HP Probook 6570b. I created a BigSur USB-Installer with a Macbook. Now when I try to boot from the USB-Stick it doesn't work. In the next part I will explain my different aproaches to boot from the stick and what happend fails. I tried three different Boot-Methods. 
1. Select the USB-Stick as bootmedium. In this case my normal windows partition boot.
2. Select "Boot from extern media". In this case the boot menu freezes. The mouse and keyboard aren't usable any more.
3. Select the efi file on the usb to boot. In this case the screen turn black.

I followed your guide step by step and I have a low resolution screen. I reflashed the BIOS multiple times with multiple versions and reseted the settings. My two guesses for the error would be 1. the BIOS is broken and 2. the USB 3.0 Stick isn't working and I need a 2.0 Stick. Or, another guess that comes to my mind, do I need exactly a 16GB USB-Stick or should be larger also okay?
Is this a known issue? What could be the problem? And how could I solve it?

**Comment by Berstanio** [comment]
Okay, I'm sorry I try to explain it better/use images.
First of all I want to boot from the installation stickt. So I press F9 at startup and get into this menu
![20210317_201409](https://user-images.githubusercontent.com/25866590/111525533-037aff00-875e-11eb-9845-a132b44db99d.jpg)

From there the first attempt to boot from the stick is selecting him in the shown menu(6. Entry). If I do my internal hard drive boots with windows(don't have a image for that, it's just windows booting).

The second attempt is to select the "External USB Hard Drive" option. After selecting it my boot menu freezes.
![20210317_202153](https://user-images.githubusercontent.com/25866590/111526132-a5025080-875e-11eb-8e0f-c3c33374286c.jpg)

My last attempt is to select the efi-file to boot from. In the next menu I select my usb-stick and navigate to the efi-file.
![20210317_201429](https://user-images.githubusercontent.com/25866590/111526295-d9760c80-875e-11eb-9c44-32d48195c202.jpg)
After selecting the efi-file my screen turnes black but the background light is still on.
![20210317_201437](https://user-images.githubusercontent.com/25866590/111526413-01657000-875f-11eb-8aa2-f27d3b02afc8.jpg)

I hope it gets now more clear what the problem is! If anything is still missing just let me know.

**Comment by chris1111** [comment]
never see this ? No image of OC Gui looks like a USB installer problem
you can try VboxHFS

**Comment by Berstanio** [comment]
Okay I will try it when I have time. Also I think i will try different USB-Sticks, maybe the stick is broken or 3.0 isn't working. I think I will also try other installer sticks for other OS to look whether this is a general problem for booting from a stick on my laptop. I will report when I know whether this is a problem specific for the macOS installer or a problem with the stick/laptop etc.

**Comment by chris1111** [comment]
> Okay I will try it when I have time. Also I think i will try different USB-Sticks, maybe the stick is broken or 3.0 isn't working. I think I will also try other installer sticks for other OS to look whether this is a general problem for booting from a stick on my laptop. I will report when I know whether this is a problem specific for the macOS installer or a problem with the stick/laptop etc.

what is the Graphics card

**Comment by Berstanio** [comment]
It is a Intel HD Graphics 3000.

**Comment by chris1111** [comment]
6570b Intel HD3000 are you sure?

**Comment by Berstanio** [comment]
Yes that is what the device manager of windows says. And Probook 6570b is written on the laptop.

**Comment by chris1111** [comment]
see bios Infos

**Comment by chris1111** [comment]
You have a i3 cpu ?

**Comment by chris1111** [comment]
If you have a Probook 6570b i3 Intel HD 3000 CPU you have to follow this guide but Intel HD 3000 Support stop at High Sier 10.13
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator

This is the first time Isee 6570b HD 3000 🥸
