### ISSUE TITLE
Initial Installer does not run (MacBook Air 2020 M1)

### ISSUE THREAD

**Issue by slipdip123** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#56]
I don't know if this is an issue with Apple Silicon, but the USB installer is seemingly hung on "Installing macOS wait . . . .". Here is a screenshot:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/38812289/112683494-8dffe480-8e69-11eb-9bbf-6ccb886da71b.png">

I have given the program over an hour to run, SIP is disabled and so is gatekeeper. I ran caffeinate -d in another terminal to make sure my Mac doesn't sleep. Is there anyway I can fix this?

**Comment by slipdip123** [comment]
Apparently the installer just wanted another hour, probably my USB drive I assume. Really sorry about this.

**Comment by chris1111** [comment]
A normal USB drive take about 30 minutes for Big Sur Installer
