### ISSUE TITLE
Can’t boot HP ProBook 4540s

### ISSUE THREAD

**Issue by slipdip123** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#57]
I have put macOS Big Sur on the USB, and I have configured the bios correctly for my computer. When I try to boot through the USB, it just boots from my SSD, and when manually navigating to the EFI file, it hangs with the screen still on but nothing showing. How can I get my machine to boot?

**Comment by slipdip123** [comment]
After looking up normal hackintosh guides, I have found that my graphics is the issue. Intel HD graphics 3000 only work with high Sierra and below.

**Comment by chris1111** [comment]
See here
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator
