### ISSUE TITLE
Cant get bluetooth and wifi kexts to work...hp probook 6570b

### ISSUE THREAD

**Issue by FammasMaz** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#6]
I followed your guide...everything is working. but when I add bluetooth and airport fixup kexts to config.plist via opencore configurator...i get a kernel panic. 

I placed the kexts you mentioned on your github package creator guide into OC/kexts/
I ran opencore configurator 2.10 and added those 4 kexts into the plist. I used 2.10 as the latest configurator versions were not giving me an option to add the kexts into plist (selection area greyed out). 

I did these steps but still getting kernel panic. 

Also, can you tell how can I get ar9285 to work? i don't have a Broadcom card tho and seems like you don't use the kexts for atheros...

**Comment by FammasMaz** [comment]
[Uploading EFI.zip…]()
this is my efi...getting kernel panic on it

**Comment by FammasMaz** [comment]
This is my efi
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5386604/EFI.zip)

**Comment by chris1111** [comment]
You not need to place any kext the kext is already place if you place the kext its a different kext that why you have KP

**Comment by FammasMaz** [comment]
I cant boot with the already placed ones. can you share your efi...i see that you have the same laptop as mine

**Comment by chris1111** [comment]
Impossible!  read the guide and follow exact steps
