### ISSUE TITLE
I'm getting error when I'm trying to make the USB Installer

### ISSUE THREAD

**Issue by johncodeos** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#66]
When I'm making the USB installer with the 'Install Media HP Laptop OC', after the Disk Utility step, I'm getting the following message:
<img width="420" alt="Screen Shot 2021-04-18 at 5 12 05 PM" src="https://user-images.githubusercontent.com/11445928/115400211-ac02ff80-a1f1-11eb-8b64-74a71b8c5dd8.png">

I followed the video tutorial, but I keep having the same error.

**macOS Catalina 10.15.7**

**Comment by chris1111** [comment]
SIP is not fully disable
