### ISSUE TITLE
EliteBook 2570p

### ISSUE THREAD

**Issue by andrea-falco** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#67]
Hi,
I followed your guide and your videos and everything went well, **thank you** very much for your work.

Everything works, except:
- Trackpad, it works but in the settings I have "No trackpad found"
- Battery, I don't see the entry in the settings

Thanks! 😄 

**My EFI folder**:
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6383022/EFI.zip)

**Comment by chris1111** [comment]
what is the macOS version

**Comment by andrea-falco** [comment]
macOS Big Sur 11.2.3

**Comment by chris1111** [comment]
The setup for the battery is in the Energie Saver but I know we have an issue here
This two issue is relate to OC 0.6.9 I think? because this issue is not present with OC 0.6.8 and 0.6.7
You can try to Update some kext (SMCBateryManager.kext and VoodooPS2Controller but don't use VoodooInput.kext inside the plugin because the mousse not working anymore)
Let me know if you find the solution I will try some thing on my side
Thanks

**Comment by andrea-falco** [comment]
Ok, I'll try updating the 2 kext to the latest version.
I will keep you up to date.

Thanks!

**Comment by chris1111** [comment]
One of my friend said no issue 11.2.3 and 12.4 Beta

**Comment by andrea-falco** [comment]
Hi Chris,
I added `SMCBatteryManager.kext` in config.plist, I don't know why it was missing.
Now the battery is working and I can see the percentage and the rest of the settings.
Now I see the trackpad in the settings, but the gestures don't seem to work, is this normal?

---

Also I compared the `EFI/OC/Kexts` folder with the Kernel section of the `config.plist` file.
In the `config.plist` I don't have:
- `Intel7Series-Injector.kext`
- `RealtekRTL8111.kext`

Do these 2 have to be added to the `config.plist,` or only in some cases?

**My updated EFI folder:**
[EFI_20210427_1537.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6384936/EFI_20210427_1537.zip)

**Comment by chris1111** [comment]
> Hi Chris,
> I added `SMCBatteryManager.kext` in `config.plist`, I don't know why it was missing.
> Now the battery is working and I can see the percentage and the rest of the settings.
> Now I see the trackpad in the settings, but the gestures don't seem to work, is this normal?
> 
> Also I compared the `EFI/OC/Kexts` folder with the Kernel section of the `config.plist` file.
> In the `config.plist` I don't have:
> 
> * `Intel7Series-Injector.kext`
> * `RealtekRTL8111.kext`
> 
> Do these 2 have to be added to the `config.plist,` or only in some cases?
> 
> **My updated EFI folder:**
> [EFI_20210427_1537.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6384936/EFI_20210427_1537.zip)

Thanks 🤙
 I will check and made a correction then you will see a commit about it
If your network is Realtek you need to enable and Disable IntelMausi because is not needed

**Comment by chris1111** [comment]
Ok all is correct now testing by me here

![Untitled](https://user-images.githubusercontent.com/6248794/116327084-f2c59c00-a793-11eb-9df1-0dfa57187323.png)
