### ISSUE TITLE
support for G5 series

### ISSUE THREAD

**Issue by epifanio** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#68]
Hi, I understood this will work only with HP EliteBook G7 series - will it be possible to add support for G5 EliteBook series ? 

Thanks!

**Comment by chris1111** [comment]
Its not G7 Series its  [7 series chipset](https://www.cpu-world.com/news_2011/2011121302_Mobile_Intel_7_Series_Chipsets_Panther_Point_.html)

Probook G5 use Intel UHD Graphics 620

**Comment by epifanio** [comment]
Sorry I I read the following:

# [Support Laptop](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC#support-laptop) 
* ☞ 7 series laptop HP Probook EliteBook * Ivy Bridge * . Support macOS Sierra 10.12 to macOS Big Sur 11

and I thought that was possible to add support for the G5 as well.
I understood maybe OSX 11.0 will not be possible on the G5, do you have any suggestion on which guide to follow, to have an older OSX version (15.x?) installed on a HP Elitebook 840 G5 ?

**Comment by chris1111** [comment]
It is possible for BS this guide probably works for you 
https://www.insanelymac.com/forum/topic/335269-hp-840-g3-elitebook-wifi-and-bluetooth-resolved-big-sur-catalina/
