### ISSUE TITLE
Brightness control no longer works under macOS Big Sur 11.3 - HP Elitebook 8470p

### ISSUE THREAD

**Issue by schlusenbaum** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#69]
After updating macOS from Big Sur 11.2 to 11.3 on my HP Elitebook 8470p, the brightness control no longer works. Neither via the control center nor via the buttons.

**Comment by chris1111** [comment]
use the latest program its fix few weeks a go

**Comment by schlusenbaum** [comment]
hello chris1111,
I just installed my 8470p with Big Sur 11.2 last week with the latest version of the HP-Probook-EliteBook-Package-Creator-OC available.
There the brightness control worked!

Only with the update to Big Sur 11.3 it no longer works.

**Comment by chris1111** [comment]
its work here 11.3 and 11.3.1 and 11.4

**Comment by schlusenbaum** [comment]
strange.
The computer runs perfectly otherwise, how can I solve this?
Can I run the HP Probook EliteBook Package Creator OC over it again? However, I now have OC 0.7.0 on it.
It can't be because of the new OpenCore version, because it didn't work with OC 0.6.3 under Big Sur 11.3.

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/discussions/71

**Comment by schlusenbaum** [comment]
The brightness control still does not work on the 8470p after updating from Big Sur 11.2.3 to 11.3, 11.3.1 or even 11.4 Beta.
I have even completely reinstalled 11.3.
--> Brightness control does not work
--> downgrade to 11.2.3 --> brightness control works.

I think the DSDT probably has to be edited here, but I have absolutely no idea about it.

**Comment by afzl-wtu** [comment]
> its work here 11.3 and 11.3.1 and 11.4 See picture
> 
> ![Screen Shot 2021-05-04 at 10 19 48 AM](https://user-images.githubusercontent.com/6248794/117018497-8af6e000-acc2-11eb-9c57-68d81382fe63.png)

May I know which Programs you use in your hackintosh I see many programs on your menu Bar. I would like to follow you. Please tell me which tools and apps you have in your mac. Also I see you use 1333MHz Ram . It is slower Ram use 1600 MHz.
