### ISSUE TITLE
OpenCore not see drive

### ISSUE THREAD

**Issue by sajtos888** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#7]
Hi! There is a problem i can't see the drives at opencore neither external nor windows.
Sorry i was careless i wrote in the wrong place before.

Thaks Sajtos888
![20201115_201407](https://user-images.githubusercontent.com/70166390/99194743-c12abc80-2781-11eb-8c09-2e26e50f80cc.jpg)

**Comment by chris1111** [comment]
macOS is the drive

**Comment by sajtos888** [comment]
But there is another SSD in the machine that has windows.
if I boot from USB you will see all the drives

**Comment by chris1111** [comment]
don't know man I have Windows UEFI and its show on boot screen

**Comment by sajtos888** [comment]
You can see all the drives at USB boot.
![20201115_203916](https://user-images.githubusercontent.com/70166390/99194939-fe437e80-2782-11eb-9f24-e626cc48a716.jpg)

**Comment by chris1111** [comment]
probably you have change some thing in the EFI

**Comment by sajtos888** [comment]
Nothing! Now fresh installation is not beta big sur.

**Comment by chris1111** [comment]
> Nothing! Now fresh installation is not beta big sur.


I have new Big Sur release and no issue here
![Screen Shot 2020-11-15 at 2 55 12 PM](https://user-images.githubusercontent.com/6248794/99195349-1ef3e000-2753-11eb-900d-4e951b81cdd3.png)

![15195316](https://user-images.githubusercontent.com/6248794/99195345-1a2f2c00-2753-11eb-95df-a1dc36ac8c0c.png)

**Comment by sajtos888** [comment]
I did everything based on your writing.  It is likely that something else will be the problem.

2 SSD is in the machine separately and if the boot outer from the USB is then all plates If SSD is bootol then I only see the MAC disk

**Comment by sajtos888** [comment]
I noticed that the drivers disappear after installing the HP-ProBook-Elite-Bokk-macOS.pkg package

**Comment by sajtos888** [comment]
I mean the drive

**Comment by chris1111** [comment]
> I mean the drive


If your Windows is UEFI not suppose to be a problem maybe check the bios setup ?

**Comment by sajtos888** [comment]
Unfortunately, I find everything okay.  So far, there has been nothing wrong with the BETA version.  Here, too, there is nothing wrong with the system itself just that I can't see the other disks.

**Comment by chris1111** [comment]
did you reset de NVRAM

**Comment by sajtos888** [comment]
Unfortunately i tried and it doesn't work.  But I can start windows from the boot menu so maybe I'm used to it.  :D

**Comment by chris1111** [comment]
Wait !
I am in test now maybe its an OC update you need I will gives you the solution

**Comment by sajtos888** [comment]
Ok i am waiting  In the meantime, thank you!

**Comment by chris1111** [comment]
Send me you config.plist of the SSD

**Comment by chris1111** [comment]
Hello  
![296233927](https://user-images.githubusercontent.com/6248794/99292561-6049c580-280f-11eb-97ba-75495f21bd28.gif)

**Comment by sajtos888** [comment]
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5549000/config.plist.zip)

**Comment by chris1111** [comment]
Try this 
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5549017/config.plist.zip)

**Comment by sajtos888** [comment]
Ahh it works thank you very much!  You are a gentleman! :D :D
![20201116_194810](https://user-images.githubusercontent.com/70166390/99294945-111e8780-2845-11eb-8ad0-ba60fdab9546.jpg)

**Comment by chris1111** [comment]
I have Update the config in the program I will also update OC and the HP theme 2  in a few minutes 

here the Theme HP 2 you can try
[Resources.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5549047/Resources.zip)

**Comment by sajtos888** [comment]
Super works for everyone! :)
![20201116_195722](https://user-images.githubusercontent.com/70166390/99295800-22b45f00-2846-11eb-8602-5036ea7aa00f.jpg)

**Comment by chris1111** [comment]
> Super works for everyone! :)
> ![20201116_195722](https://user-images.githubusercontent.com/70166390/99295800-22b45f00-2846-11eb-8602-5036ea7aa00f.jpg)

Thanks 😀 😇 You can take a screenshot with OpenCore just hit F10 
the image is store on the EFI Partition 
![16190517](https://user-images.githubusercontent.com/6248794/99296707-2a0f4480-2815-11eb-92e7-061f4fc88899.png)

**Comment by sajtos888** [comment]
Thanks for the advice! :smile: 

![16191020](https://user-images.githubusercontent.com/70166390/99297072-087b8080-2848-11eb-97be-d9e7c39b56cd.png)

**Comment by chris1111** [comment]
I have to Big Sur internal and my windows 10 SSD is on eSATA external case SSD 
😆
![16191236](https://user-images.githubusercontent.com/6248794/99297537-655e4300-2816-11eb-98b8-7d0eacede598.png)

**Comment by sajtos888** [comment]
that's nice! :smile:
