### ISSUE TITLE
Dim screen on HP 8470p w/i7-3630qm + HD4000

### ISSUE THREAD

**Issue by justinqian42** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#73]
Hi Chris,

Thanks for your hard work! Much appreciate it!

Here's the only issue after I installed Big Sur on my HP 8470p: dim screen (roughly 70% max brightness)

Having done some investigation, I found that it could be related to the default PWMMAX value that's associated with the spoofed model MacbookPro13,1.

For Skylake, the backlight-level is 0x56c.

However, for Sandy/Ivy Bridge, the value should be 0x710.

Tried changing the UID from 0x10 to 0x14 in SSDT-PNLF.aml, according to https://raw.githubusercontent.com/RehabMan/OS-X-Clover-Laptop-Config/master/hotpatch/SSDT-PNLF.dsl. And the brightness is back to the maximum without brightness adjustment.

Also tried to set the "backlight-level" value to 0x710 in config.plist, but it just didn't work as the value remains 0x56c every time the laptop boots up.

You seemed to have spoofed the model to Coffee Lake which injected 0xffff as the PWMMAX value. Seems like it worked but not sure if it would damage the hardware.

Any idea have this issue fixed?

I'm still trying some other methods but could hardly find references for HD4000 with Big Sur.

Thank you in advance!
Best Regards,
Justin

**Comment by justinqian42** [comment]
Just realised that the UID is HEX.
0x10 = 16
0x14 = 20 which doesn't mean anything...

Alright.... now testing other values...

**Comment by chris1111** [comment]
Slider not working with 0x10

**Comment by chris1111** [comment]
You can talk with [MaLd0n](https://www.olarila.com) for trying a solution 
Open a topin in the forum

**Comment by justinqian42** [comment]
Thanks Chris for your prompt reply.
I have fixed the issue.
Just simply set UID to 0x0E in SSDT-PNLF.aml, which is namely 14 in decimal, representing Sandy/Ivy Bridge. This will increase the PWMMAX to 0710.
To ensure WhateverGreem takes over the backlight adjustment job, add applbkl=1 into the boot-args.
![Screen Shot 2021-06-24 at 22 04 59](https://user-images.githubusercontent.com/49712643/123260211-a8b12a80-d538-11eb-9394-56dc7227e9dc.png)

I believe this issue is related to some previous ones that other people reported.

**Comment by chris1111** [comment]
Thanks I will try

Where you see the applbkl=1 relation with WEG ?
https://github.com/acidanthera/WhateverGreen

**Comment by justinqian42** [comment]
> Thanks I will try
> 
> Where you see the applbkl=1 relation with WEG ?
> https://github.com/acidanthera/WhateverGreen

See this

_applbkl=0 boot argument (and applbkl property) to disable AppleBacklight.kext patches for IGPU. In case of custom AppleBacklight profile- read here._

Set applbkl=1 is to explicitly force WhateverGreen to take over the brightness adjustment just in case anyone accidentally set it to 0 as he/she troubleshoots the same issue. The value should be 1 by default, though.

**Comment by justinqian42** [comment]
New finding -- change the value to 0x0F will force the PWMAX to be 0x0AD9. This is much closer to the real max brightness, though it's still a little dimmer (roughly 5% less).
Very happy with it.
![Screen Shot 2021-06-25 at 10 22 14](https://user-images.githubusercontent.com/49712643/123350878-3d4e7380-d59f-11eb-92da-4821276926a2.png)

**Comment by chris1111** [comment]
You should answer the questions first
Where you see the applbkl=1 relation with WEG ?
https://github.com/acidanthera/WhateverGreen

**Comment by chris1111** [comment]
> > Thanks I will try
> > Where you see the applbkl=1 relation with WEG ?
> > https://github.com/acidanthera/WhateverGreen
> 
> See this
> 

AppleBacklight profile- read here._


You said read here 

Were ?

**Comment by justinqian42** [comment]
> > > Thanks I will try
> > > Where you see the applbkl=1 relation with WEG ?
> > > https://github.com/acidanthera/WhateverGreen
> > 
> > 
> > See this
> > AppleBacklight profile- read here._
> 
> You said read here
> 
> Were ?

That’s the statement on WhateverGreen github page. I just did copy-paste. Follow the hyperlink there please.

**Comment by chris1111** [comment]
> > > > Thanks I will try
> > > > Where you see the applbkl=1 relation with WEG ?
> > > > https://github.com/acidanthera/WhateverGreen
> > > 
> > > 
> > > See this
> > > AppleBacklight profile- read here._
> > 
> > 
> > You said read here
> > Were ?
> 
> That’s the statement on WhateverGreen github page. I just did copy-paste. Follow the hyperlink there please.


applbkl=1 is not mentioned anywhere and that's why I ask you the question

**Comment by afzl-wtu** [comment]
> Hi Chris,
> 
> Thanks for your hard work! Much appreciate it!
> 
> Here's the only issue after I installed Big Sur on my HP 8470p: dim screen (roughly 70% max brightness)
> 
> Having done some investigation, I found that it could be related to the default PWMMAX value that's associated with the spoofed model MacbookPro13,1.
> 
> For Skylake, the backlight-level is 0x56c.
> 
> However, for Sandy/Ivy Bridge, the value should be 0x710.
> 
> Tried changing the UID from 0x10 to 0x14 in SSDT-PNLF.aml, according to https://raw.githubusercontent.com/RehabMan/OS-X-Clover-Laptop-Config/master/hotpatch/SSDT-PNLF.dsl. And the brightness is back to the maximum without brightness adjustment.
> 
> Also tried to set the "backlight-level" value to 0x710 in config.plist, but it just didn't work as the value remains 0x56c every time the laptop boots up.
> 
> You seemed to have spoofed the model to Coffee Lake which injected 0xffff as the PWMMAX value. Seems like it worked but not sure if it would damage the hardware.
> 
> Any idea have this issue fixed?
> 
> I'm still trying some other methods but could hardly find references for HD4000 with Big Sur.
> 
> Thank you in advance!
> Best Regards,
> Justin

Hey Dear Thanks a lot for your Solutions here. I had already posted this issue #47 . But I could not solve it. Because I am not much technical as you are. So I left Hackintosh and moved to Windows 10 and now 11. also I am really happy that you have Hp EliteBook 8470p same as mine. I will now install Mac Os Monterey and all credit goes to you for this.
I tried to search your contact over GitHub but I could not so I followed you on GitHub. I will be grateful to you if you share me your WhatsApp or Discord. Thanks a lot.
