### ISSUE TITLE
3.5 mm 3 pole external microphone not Working

### ISSUE THREAD

**Issue by afzl-wtu** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#74]
Hey Chris,
   I have HP Elitebook 8470p with Big Sur followed all your steps. Everything is perfect. The only problem is It does not record any audio from a 3.5 mm 3 poles external mic. But it works flawlessly on Windows 10 and 11. I have another mic of 3.5 mm with 4 poles, It works great. But Hackintosh does not support 3 pole microphone. Please Help me I know you are Guru.
I am attaching  System Report here. You can also see it is recognized by Mac but It is like a silent mic.
[MacBook Pro.spx.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/6776928/MacBook.Pro.spx.zip)

Besides it everything Works great Speakers are working great internal mic works great, I also have fixed the brightness issue by putting UID value 12 (Hex) in SSDT-PNLF.aml. It is even more bright now than windows.

**Comment by chris1111** [comment]
First use the HP ProBook Elitebook macOS program and it should be better for you

**Comment by afzl-wtu** [comment]
> First use the HP ProBook Elitebook macOS program and it should be better for you

Hey, I am already using your package creator Program. That is why I am here.

**Comment by afzl-wtu** [comment]
I have only Changed SMBIOS on your saying issue #47 .
