### ISSUE TITLE
Boot without USB=kernel panic

### ISSUE THREAD

**Issue by ostadnart** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#75]
I had install big sur by your guide from 4 month ago.
My wifi card was atheros 9280,today i replace it by AzureWave Broadcom BCM94352HMB model,but after that my probook 4540s
![P_20210827_033816](https://user-images.githubusercontent.com/69670261/131049611-2eb58823-be8f-447c-8f6e-465618c34a12.jpg)
 can't boot.so i reinstall big sur by usb installer(that installed big sur 2 month ago) but now it after installation complited and reboot to desktop,stuck at page that i attached.
Any help?

**Comment by chris1111** [comment]
Catalina ?

**Comment by chris1111** [comment]
Send me the EFI folder of the SSD 
Put on ZIP here I will chek tomorow for you

**Comment by ostadnart** [comment]
Big sur

**Comment by chris1111** [comment]
Send me the EFI folder of the SSD
Put on ZIP here I will chek
