### ISSUE TITLE
No graphics acceleration on HP8470p -  Mac Monterey Beta (21A5506j)

### ISSUE THREAD

**Issue by thienluong89** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#76]
Hi Chris,
Thanks for your tools help me much more easy setup MacOS on my HP laptop (HP8470p with i5-3320M and graphics HD4000, no dGPU).
Yesterday when I try with Monterey Beta (21A5506j), after post install I still have problem with graphics acceleration, even machine detect Intel HD graphics 4000 and show 1536 MB VRAM but animation still very slow and no transference on dock and menu bar.
In attached file is my Installer log and EFI folder. Could you help to find the root cause of this issue?
[EFI and log file.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7114722/EFI.and.log.file.zip)

**Comment by thienluong89** [comment]
More detail about my laptop, uploaded here for your reference
[System report.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7115890/System.report.zip)

**Comment by chris1111** [comment]
Your Log is correct Patch DSDT perfect , EFI perfect 
Compilation complete. 0 Errors, 7 Warnings, 56 Remarks, 1894 Optimizations
I have No issue with Monterey Beta (21A5506j) Update  Friday 03 Sept 2021
![scree291](https://user-images.githubusercontent.com/6248794/132216995-e4ea4f74-ae3b-40ed-b42f-0bbe3f8cb5c5.png)
you have a High Screen resolution 1600x900 
You need add this boot args 
**-igfxvesa**
See 
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/2#issuecomment-679373248

**Comment by thienluong89** [comment]
Hi Chris, - ivgfxvesa purpose for terminated graphics acceleration, I am right? Now my problem is no graphics acceleration after post installation and as you can see in my boot flag don't have this flag.
If I add - igfxvesa it mean that always force terminated graphics acceleration. So how can I get graphics acceleration. Sorry if my understanding is not correct.

**Comment by chris1111** [comment]
How did you installed MacOS if you not use the boot args ?
You are rigth this boot args is not for post Install ! Sorry
I see your system Report and all is perfect 
![Capture d’écran, le 2021-09-06 à 09 12 41](https://user-images.githubusercontent.com/6248794/132222756-f12b9730-9fc5-490a-80eb-11ef920a5527.png)


So Reinstall the patch HD 4000

**Comment by thienluong89** [comment]
Hi Chris,
I am using DeviceProperties key in the below picture. Because I am using an external display, so I need to modify it a little bit for me.
![Screen Shot 2021-09-06 at 20 20 04](https://user-images.githubusercontent.com/66806635/132224013-52347275-4af0-4e0e-969c-4068e0346a10.png)
Anyways, finally I got graphics acceleration now, but not sure it is stable or not.
The story is:
1. I try - igfxvesa boot flag as you mention in the previous post. Of course, after NVRAM reset -> restart VRAM only 5MB.
2. Then I need to remove it and restart, NVRAM reset -> MacOS: but panic
3. I try NVRAM reset 1 time, and restart but still panic. Reset NVRAM 2 times and still panic
4. Last one I do NVRAM reset 3 times before going to MacOS and this time I got graphics acceleration.
I have same problem when I am in Big Sur 11.5.2 and can not explain why and how it happend.

**Comment by chris1111** [comment]
If you modifying config.plist make sure your make the good things
Issue are Closed
Thanks to report

**Comment by thienluong89** [comment]
Hi Chris,
It seem graphics acceleration just got temporary only 1 time. After restart machine, it back to no graphics acceleration. I already try path HD4000 again, and also using Opencore Legacy patcher for post install volume path but no effect. Do you have any comment for this case?

**Comment by chris1111** [comment]
You are mixte Program probably thats the reason this is bad idea

**Comment by thienluong89** [comment]
Hi Chris,
Yeah, you are correct, it is not good way to find the root cause. Before I using Opencore Legacy Patcher I already try 3 or 4 times patch with HD4000 but still fail. So I just think what happen if I try Opencore Legacy Patcher.
You can see screen picture, even NVRAM and another thing is correct but no graphics acceleration enable. dock and menu bar still blur and animation very slow. Also in Graphics/Display hardware don't mention "Metal Family:	Supported, Metal GPUFamily macOS 1" as when graphics acceleration work.
![Screen Shot 2021-09-07 at 23 33 01](https://user-images.githubusercontent.com/66806635/132380848-77b5d3f0-dda2-4289-ab82-172e526e62b1.png)
Do you think we need reinstall MacOS and try again?
I have no ideal right now.

**Comment by thienluong89** [comment]
One point I need mention here is: some time when I try another config from USB and got fail. After NVRAM reset and boot to Mac as normal, graphics acceleration is enable. But when I restart it come back no graphics acceleration. How do you think about it?

**Comment by chris1111** [comment]
You have to stay in one program, OCLP install things for mac so its not the good Idea my program install only the kext and Fraworks and Inject other kext from bootloader
So you have the choice

**Comment by thienluong89** [comment]
If so, let me do fresh install MacOS and path HD4000 again. Will tell you if there is still facing this issue.

**Comment by chris1111** [comment]
its probably relate to your patch for the external Monitor ?

**Comment by thienluong89** [comment]
Do you have any another method for use external monitor through DP port? I don't know another method to use this port. And another question is when selecting patch option (post install) , should I choose HDMI high solution? (my laptop has DP port, not HDMI port)

**Comment by chris1111** [comment]
I have also Diplay port and no issue because its a Low screen 
This a know issue for High screen laptop
Rettry Install without the choose HDMI high
let me know

**Comment by thienluong89** [comment]
Hi Chris,
It is same problem when I install w/o HDMI high.
![Screen Shot 2021-09-08 at 22 41 20](https://user-images.githubusercontent.com/66806635/132541301-47b839c4-2356-484f-abe1-82ec4d905aab.png)

**Comment by chris1111** [comment]
Thats Confirm issue is relate to the External Monitor (Patch)

**Comment by thienluong89** [comment]
So, how can I fix it? At last time I don't modify config for external display but still fail graphics acceleration as you can see on above picture.

**Comment by thienluong89** [comment]
> Thats Confirm issue is relate to the External Monitor (Patch)
My 2nd question is: when I use with or w/o config modify for external display the result come out are same. So how can you define that this issue due to external display patch?

**Comment by chris1111** [comment]
What is the issue if you use the original config.plist?
Because its already test by a lots of User without issue

**Comment by thienluong89** [comment]
Hi Chris. It is still no graphics acceleration as you can see above picture. I don't know what happened on other users but every time when I try on my laptop always happened this issue with original config.plist.

**Comment by chris1111** [comment]
1536mb VRAM this is what I see

**Comment by thienluong89** [comment]
Yes. But you can see the dock and menu bar is solid color, not transparent. And the animation very slow. That is all I want to say from start this topic until now. I already got 1536MB VRAM, from when I start this topic, I just want report that dock and menu bar is solid color and animation very slow.

**Comment by chris1111** [comment]
If Monterey not working for you use Big Sur native HD 4000
