### ISSUE TITLE
help please...

### ISSUE THREAD

**Issue by sacheats** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#77]
Hi chris, thank you so much for the hd graphics 4000 solution!

 i installed monterey 12 on my hp probook 6470b and everything works fine.

But my processor is the i7 3720qm and its turbo boost is 3.60 ghz. However the turbo boost is never activated. The frequency always goes only up to 2.60 ghz. Can you help me?

**Comment by chris1111** [comment]
Make an [SSDT Power management ](https://github.com/Piker-Alpha/ssdtPRGen.sh)
Put SSDT.aml in ACPI and make sure is Enable in config.plist

**Comment by sacheats** [comment]
I get this message 

System information: macOS 12.0 (21A5506j)
Brandstring: "Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz"

Version: models.cfg v171 / Ivy Bridge.cfg v150


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro13,1' with board-id [Mac-473D31EABEB93F9B]
Ivy Bridge Core i7-3720QM processor [0x306A9] setup [0x0704]
With a maximum TDP of 45 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 2600 MHz)
Number of Turbo States: 10 (2700-3600 MHz)
Number of P-States: 25 (1200-3600 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

Error: board-id [Mac-473D31EABEB93F9B] not supported by Ivy Bridge – check SMBIOS data / use the -target option

Do you want to continue (y/n)?

**Comment by chris1111** [comment]
Contunue **Y**

**Comment by sacheats** [comment]
> Continue **Y**

Hi chris, turbo mode is now working. But I lost the sound. Did i do something wrong?

I just renamed the two generated files and threw them into the ACPI folder (open core)

![38346F40-A5A9-4536-9935-6B769F849F91_4_5005_c](https://user-images.githubusercontent.com/21047444/134028621-d9564fdd-d213-4f6b-82eb-00aa79684602.jpeg)
![00132D89-E620-401A-874A-D785C846900B_4_5005_c](https://user-images.githubusercontent.com/21047444/134028674-766b597f-b932-4633-bf6a-84c8f72bd526.jpeg)

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/77#issuecomment-922369367

**Comment by sacheats** [comment]
> [#77 (comment)](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/77#issuecomment-922369367)
> I told you this
> Put **SSDT.aml** in ACPI and make sure is Enable in config.plist


perfect chris, now everything is working now! Thank you so much for this <3
