### ISSUE TITLE
When booting to install, nothing shows

### ISSUE THREAD

**Issue by alamboglia** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#8]
Hi Chris first of all thanks for all the work you're doing

I have an HP Elitebook 8470p i followed all your instructions
i boot from the usb it goes through all the verbose stuff and then when it supposed to load the install it just shows a blank screen. I have an external monitor connected though displayport and it shows the mouse and I can move it but the main laptop screen is just black (its on it shows but nothing).

Any advise? I followed the instructions on your video to the letter...

**Comment by alamboglia** [comment]
Forgot to mention I used the release version of Big Sur, made all the procedure from Mojave in the same computer

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/2

**Comment by alamboglia** [comment]
It worked perfectly for the installation. following your steps now I got into the desktop but displayport not working.
I dont have hdmi in my machine, but I installed the hdmi high patch in the package creator. but now I again get the grey screen in the laptop screen but my displayport is working. any clues? If I add the -igfxvesa i wont have hardware acceleration is that right?

**Comment by alamboglia** [comment]
when using the package creator i installed my 4000 series high plus the hdmi high just so you know aparte from the other things.

**Comment by chris1111** [comment]
I dont understand what you said ????????

**Comment by alamboglia** [comment]
Again. After installation my internal display works good but the displayport is not sending signal

**Comment by alamboglia** [comment]
I tried to install the hdmi high version from the instal hp probook elitebook package, but then what happened is that the displayport works but the internal display doesnt show anything

**Comment by chris1111** [comment]
Dispalyport not working on High Screen 1600x900

**Comment by alamboglia** [comment]
High Screen of the internal display or high screen of hdmi?

**Comment by chris1111** [comment]
> High Screen of the internal display or high screen of hdmi?

No the screen of laptop , its a resolution screen

**Comment by alamboglia** [comment]
so I should install the low version of my laptop display?

**Comment by chris1111** [comment]
> so I should install the low version of my laptop display?

No you have a High resolution screen and its known issue for the display port

**Comment by alamboglia** [comment]
ohhhhh ok ok so it wont work at all

**Comment by alamboglia** [comment]
so I shouldnt install the hdmi either version because i dont have it anyways, it has nothing to do with the displayport?

**Comment by alamboglia** [comment]
Any chance  you'll have a fix for this later on? I have the displayport only to have an external monitor.  I would really appreciate it anyways thanks for the support.

**Comment by chris1111** [comment]
No chance but you can try by your self google issue of laptop model?

**Comment by alamboglia** [comment]
well actually I was in mojave and it was working perfectly displayport + the high resolution display. Thats what I ment if there was a problema now with BIG SUR...
