### ISSUE TITLE
HWMonitor doesn´t show Frequencies 

### ISSUE THREAD

**Issue by paasoares** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#80]
Hi Chris, Sorry to nag you...
I followed the instruction and apparently everything is working fine.
But, HWMonitor is not showing any CPU frequencies :
![Screenshot 2021-09-21 at 17 01 32](https://user-images.githubusercontent.com/1421196/134205954-e5c1a7cf-26ce-4a2f-8e11-1d82c7b1c423.png)
So, i'm in doubt if the correct cpu is being used with the correct power stages
Can you help ?

**Comment by chris1111** [comment]
Seriously 

What you think of this infos

![134205954-e5c1a7cf-26ce-4a2f-8e11-1d82c7b1c423](https://user-images.githubusercontent.com/6248794/134208567-e3ba92a3-42fe-487f-92bc-cbd70d9ca69b.png)
