### ISSUE TITLE
Elitebook 8470p no DisplayPort 

### ISSUE THREAD

**Issue by alamboglia** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#84]
I just installed your package creator Big Sur and everything worked perfect I did it downloading the latest version which says has the fix for the DisplayPort Intel 4000 high. Im still no getting the DisplayPort to work perhaps something I did wrong>?

**Comment by chris1111** [comment]
send EFI folder on ZIP and ioreg

**Comment by alamboglia** [comment]
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7217204/EFI.zip)
[ioreg.pdf](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7217227/ioreg.pdf)

thanks for the help men

**Comment by chris1111** [comment]
Needs IOREG
**MacBook Pro of chris.ioreg.zip**

**Comment by alamboglia** [comment]
Im sorry I know where to find the MacBook Pro of lamboglia but how exactly do I send you that information?

**Comment by chris1111** [comment]
Save an Ioreg and ZIP

**Comment by alamboglia** [comment]
[MacBook Pro of alamboglia.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7217977/MacBook.Pro.of.alamboglia.zip)

Ok here it is

**Comment by chris1111** [comment]
Its not an IOREG

**Comment by alamboglia** [comment]
sorry then I don't know what is an IOREG where do I find it ? and I'm sorry for taking so long in getting you the info

**Comment by alamboglia** [comment]
ok I found a guide to do it, gimme some minutes

**Comment by chris1111** [comment]
Nothings wrong with your IOREG I dont have the hardware 1600x900 but I dont know whats wrong with your
Its already test and report working
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/discussions/79

**Comment by alamboglia** [comment]
![WhatsApp Image 2021-09-23 at 9 04 02 AM](https://user-images.githubusercontent.com/74522064/134521967-7ab61a16-d721-4737-92be-39da3a8f04a2.jpeg)

I took out the reference from #79 out of config.plist and when restarted the DisplayPort works and the integrated display just stays black. I guess that's what it was before. But it confirms the DisplayPort is working perhaps the solution in #79 doesn't work for all? Any guess on a workaround?

**Comment by chris1111** [comment]
Ok so the diferance is only this
framebuffer-patch-enable 2 insteed of 1

**Comment by chris1111** [comment]
advise see my previous post

**Comment by alamboglia** [comment]
> Ok so the diferance is only this
> framebuffer-pipecount 2 insteed of 1

yep confirmed working thanks for your patience Chris1111!!!!!

**Comment by chris1111** [comment]
> > Ok so the diferance is only this
> > framebuffer-pipecount 2 insteed of 1
> 
> yep confirmed working thanks for your patience Chris1111!!!!!

Ok thanks
Fix https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/releases/tag/V1
