### ISSUE TITLE
Elitebook 8470p super slow loading time

### ISSUE THREAD

**Issue by alamboglia** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#85]
Hi Chris thanks for all your help so far. After getting Big Sur with your tools setup booting time is super slow more than 1 minute and a half. Anything I can do to speed it up?

**Comment by chris1111** [comment]
never see this ; the boot time is suppose to be 20 sec
see what's block in verbose mode

**Comment by alamboglia** [comment]
yep I have ssd and had a mojave installation before with Clover and it was 16 seconds boot time, thats why i knew it was weird. Remember in the previous issue (display port ) I sent my config.plist and ioreg and you said everything was ok.

**Comment by alamboglia** [comment]
Is there any way I can copy the entire verbose loading so i can check what could be happening? it goes very fast cant read anything.

**Comment by chris1111** [comment]
if it goes fast the boot is fast Thats impossible booting fast for one minutes , it certainely block somewere

**Comment by alamboglia** [comment]
Can I send you a video of the booting process?

**Comment by chris1111** [comment]
Your only setup boot log .txt  on config OpenCore you will see  the boot procees

**Comment by alamboglia** [comment]
Thanks I will look into it

**Comment by alamboglia** [comment]
> And please stop to open Isue for nothing because thats nothing to do with the Program

Well actually this is an issue because NO PROGRAM can request permission either from webcam or microphone . You verified my config.plist and IOREG before and said everything was ok so it definitely is an issue. Not trying to be rude but to get a solution which will help later for others that use your work. AGain thanks a lot for all you do I know its hard work. But this is definitely an issue.
