### ISSUE TITLE
Elitebook 8470p No Access to Camera or Microphone in apps (like zoom)

### ISSUE THREAD

**Issue by alamboglia** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#88]
I put a discussion thinking it was just for the microphone but its happening with the cameras as well, any app i install (like Zoom for example) for video and mic, Big Sur is not asking for the Microphone or Camera permission and I have tried several different things out of the internet and none work.

**Comment by chris1111** [comment]
I dont have any issue with this, some app needs to demmand  acces of Microphonne in Security and you can add the app 
exemple here with my screen recorder Ink2Go
See I have save a screen record in Documents
![Untitled1](https://user-images.githubusercontent.com/6248794/134736786-156abe02-70d1-4e56-a9c4-fe2ffad3c6e6.png)

**Comment by alamboglia** [comment]
That's the thing every app I tried that needs microphone and webcam permission wont work, and if you go to the mic and camera tabs in security and privacy they're empty. And they don't have any  + o -  to add them there.

**Comment by chris1111** [comment]
For the camera and the microphone the permissions must be requested by the applications

**Comment by alamboglia** [comment]
While reading around someople seem to think that this has to do with the csrutil enabled or disabled. I wanted to see if it was enabled or no and when i went into recovery i saw this
![Screen Shot 2021-09-24 at 4 15 20 PM](https://user-images.githubusercontent.com/74522064/134740525-511670fb-54d2-4c97-b921-fbb50ce8890d.png)
. 
The status says its unknown when it should say either enabled or disabled right? Is there a way I can fix this

**Comment by chris1111** [comment]
> While reading around someople seem to think that this has to do with the csrutil enabled or disabled. I wanted to see if it was enabled or no and when i went into recovery i saw this
> ![Screen Shot 2021-09-24 at 4 15 20 PM](https://user-images.githubusercontent.com/74522064/134740525-511670fb-54d2-4c97-b921-fbb50ce8890d.png)
> .
> The status says its unknown when it should say either enabled or disabled right? Is there a way I can fix this


This is normal its not an issue

**Comment by alamboglia** [comment]
> For the camera and the microphone the permissions must be requested by the applications

Again something is going on because all the applications that normally should ask for this wont do it. They are not requesting the permission. Something is going on that is blocking applications from requesting the webcam and mic permissions.

**Comment by chris1111** [comment]
Try to change the SIP value then reset NVRAM

**Comment by alamboglia** [comment]
> Try to change the SIP value then reset NVRAM

where do i change the sip value? and to what do i change it?

**Comment by alamboglia** [comment]
> > Try to change the SIP value then reset NVRAM
> 
> where do i change the sip value? and to what do i change it?

I tried to do csrutil enable then disable and it would send and error and won't let me change the status

**Comment by chris1111** [comment]
The value is set to make  HD 4000 on Monterey 12 
to do this the config is set
csr-active-config ➤ EF0F0000

**Comment by alamboglia** [comment]
> The value is set to make HD 4000 on Monterey 12
> to do this the config is set
> csr-active-config ➤ EF0F0000

do I delete this in config.plist?

**Comment by chris1111** [comment]
if you want change the value  its simple change on config.plist then reset NVRAM with OpenCore 

![clear_10](https://user-images.githubusercontent.com/6248794/134741263-245ac673-11df-463c-9922-b83699b14520.png)

**Comment by alamboglia** [comment]
Thanks yeah I know about clean nvram what Im saying is that the value you put before csr-active-config ➤ EF0F0000 is already in my config.plist. Do I need to delete it? or change it to something different?

**Comment by chris1111** [comment]
And please stop to open Isue for nothing because thats nothing to do with the Program
