### ISSUE TITLE
Displayport not working on BigSur but was working on Mojave

### ISSUE THREAD

**Issue by alamboglia** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#9]
Hi Chris I had a mojave installation of hackintosh, and i used your tool hp pro tools elitebook creator (an old one) and after using it, i had both high res laptop display (intel 4000) and my displayport external monitor. Any chance there is something different in the driver for Big Sur that is installed in the New hp package creator?

**Comment by chris1111** [comment]
send me EFI on ZIP

**Comment by alamboglia** [comment]
new efi from the installation of big sur? no problem let me zip it and attach it here

**Comment by alamboglia** [comment]
[EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/5549966/EFI.zip)

**Comment by chris1111** [comment]
I not see any thing different probably is support on Mojave but not Big Sur
I can not really help here

**Comment by alamboglia** [comment]
ok thanks man

**Comment by alamboglia** [comment]
hopefully while the days or weeks go , you can find any solution if you do please let me know thanks for your hard work!!!
