### ISSUE TITLE
Help - 9470m Monterey

### ISSUE THREAD

**Issue by paasoares** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#96]
Hi Chris,
I did a clean install of Monterey following your guide.
Everything is working (including HD4000 patch) except Audio and Bluetooth.
when booting in verbose mode I can see some ACPI errors
![boot](https://user-images.githubusercontent.com/1421196/139560477-a7406edb-dc12-444e-a7c3-6158b08307f4.jpg)
.
Can you guide me on how to solve this ?

Thanks !

**Comment by chris1111** [comment]
Check in EFI/OC/ACPI 
if you have DSDT.aml

**Comment by paasoares** [comment]
Nope..
![Screenshot 2021-10-30 at 23 53 02](https://user-images.githubusercontent.com/1421196/139560604-a10c7190-a91a-451b-ad64-b519916202b9.png)
.

**Comment by paasoares** [comment]
How/where can i grab DSDT.aml ?

**Comment by chris1111** [comment]
DSDT.aml not create
ssdt.aml is not from the program something wrong with this

**Comment by bayard1965** [comment]
You have to boot with an Opencore configuration generated by Media HP Laptop OC (no DSDT), then you you can use HP-ProBook-EliteBook-macOS.pkg to generate an EFI folder for your computer.

**Comment by paasoares** [comment]
Thanks !
Just reinstalled everything again and this time all files are in place... don´t know what happened on the previous installation
