### ISSUE TITLE
HP 8470p (i5-3320M with HD4000) hardware acceleration issue

### ISSUE THREAD

**Issue by thienluong89** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#98]
Hi Chris,
My laptop has issue with graphic on Monterey.
I attach the video for you easy understand.
https://www.youtube.com/watch?v=43xZaz-XtNg
Normally boot even I can see Graphic 1536MB but dock & menu bar still solid color (no hardware acceleration, check by VDADecorderChecker).
When I go to Apple tivi and open any tivi show/film, it will be freezed.
I need force restart by power button, after boot again dock and menu bar become normal (transparent) and I can see Hardware acceleration is fully supported (check by VDADecorderChecker).
Could you give me some advice?

**Comment by chris1111** [comment]
what is the Max resolution 1600x900?
send ZIP EFI folder here

**Comment by thienluong89** [comment]
Yes, max resolution is 1600x900.
Please find EFI in below link (sorry I don't know why can not attach the file directly here):
https://drive.google.com/file/d/1MrTHQAl3v9OS5KdN9dOEnj648sQE47HC/view?usp=sharing

**Comment by chris1111** [comment]
This is not the Original from the program
Follow the guide exactly, if you modify the OpenCore EFI dont open issue here you have to resolved your error

**Comment by thienluong89** [comment]
Hi Chris,
Let me share the original EFI from in this tonight.
The reason why I modify EFI cause by origin EFI it already happened this issue. So I try to adjust EFI but still no change.

**Comment by chris1111** [comment]
> Hi Chris, This is my origin EFI. [EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7487339/EFI.zip)

With this EFI it is impossible to have any issue on Graphics HD 4000 if you have alsoinstalled the patch HD 4000

**Comment by thienluong89** [comment]
> > Hi Chris, This is my origin EFI. [EFI.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/files/7487339/EFI.zip)
> 
> With this EFI it is impossible to have any issue on Graphics HD 4000 if you have also installed the patch HD 4000

I also install your patch HD4000 following guide but final result is fail as video.
One abnormal I can observe is when hardware acceleration fail, IMEI do not load.

**Comment by chris1111** [comment]
If failled you have to reboot and reinstalled the patch
some tim eis failled system is slow to respond

**Comment by thienluong89** [comment]
> If failled you have to reboot and reinstalled the patch some time is failled system is slow to respond

Sorry for not clear answer in my comment.
Actually, "fail" in this comment means even patch HD4000 successfully installed on my laptop but hardware acceleration still fail.

**Comment by chris1111** [comment]
You are the first unlucky one

**Comment by thienluong89** [comment]
> You are the first unlucky one

I am trying to fix it now.
As per talk in upper comment from me, when hardware acceleration fail, IMEI is not loaded.
So, do you have any method to force IMEI loaded? I think maybe it can help solve my problem.
I already try add IMEI in OC > Device properties; using SSDT-IMEI with DSM method but all of them cannot load IMEI.
